import type { Herb } from './types';

/**
 * WHICH FILE A CARD IMAGE ACTUALLY SHIPS.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * `output: 'export'` forces `images: { unoptimized: true }`, so `sizes` and `quality` are
 * inert: whichever file a component names is the file that is transferred, at whatever
 * size it is drawn. Choosing the right variant at the call site is the only lever there is,
 * which is why it is worth a named function rather than a path spelled out inline.
 *
 * THREE VARIANTS, AND EACH HAS ONE JOB.
 *
 *   image (800px) — the card as the subject of a page.
 *   thumb (400px) — a grid tile or a hero's featured card, 56-160px wide on screen.
 *   chip  (112px) — a card as one item in a strip, ~35px wide on screen.
 *
 * WHY THE CHIP IS DERIVED RATHER THAN STORED. `herbs.json` is generated by
 * `build_deck.py`, which needs the print masters; `field-cards.ts` is hand-written from
 * artwork that has no PDF in this pipeline. A `chip` field would therefore have to be added
 * twice, in two places, by two different processes. The path is mechanical — every variant
 * in this repo is `/cards/<variant>/<id>.webp` — so it is computed here and the FILE's
 * existence is what gets pinned, by `card-art.test.ts` reading the real directory. That is
 * the stronger guarantee anyway: a stored field can name a file that was never rendered.
 *
 * 112px IS MEASURED. The Field Research strip draws chips 35 CSS px wide, and 35 x 3 is the
 * most a device pixel ratio of 3 can ask for. `scripts/build_chips.py` writes them; run it
 * after any card art changes.
 * ─────────────────────────────────────────────────────────────────────────────
 */

/** The width `scripts/build_chips.py` renders, repeated here only so a test can compare. */
export const CHIP_WIDTH = 112;

/**
 * The smallest card art there is, for a card drawn as one item in a strip.
 *
 * Do not reach for this above ~37 CSS px wide: it is a fifth of the thumbnail's file size
 * because it is a fifth of its resolution, and the point is that at chip size nobody can
 * tell. Anywhere the card is meant to be looked at, name `herb.thumb`.
 */
export function chipArt(herb: Herb): string {
  return `/cards/chip/${herb.id}.webp`;
}
