import { DECK } from './deck';
import type { Herb, SourceRef } from './types';

/**
 * Independent references for each printed card, and how strong the evidence behind that
 * card's claims actually is.
 *
 * WHERE THIS CAME FROM. A card-by-card source audit: three references per card, each one
 * opened and read against what that card prints before it was brought into
 * `src/data/sources.json`. That checking is what `verified: true` means there, and it is
 * the only reason these can render at all — `resolveRefs` drops anything unverified, so an
 * unchecked citation cannot reach a reader.
 *
 * WHY IT IS NOT IN THE DECK DATA. `herbs.json` is generated by `scripts/build_deck.py`
 * from the print PDFs, and CLAUDE.md forbids hand-editing it. So the same seam that already
 * carries errata (`card-issues.ts`) carries citations: curated TypeScript over generated
 * data, joined by card number.
 *
 * WHY IT IS NOT IN `deck.ts`. `npm run sync:edge-shared` copies that module verbatim into
 * the Supabase edge function. The server has no use for bibliography — this is presentation
 * — so keeping it out of the synced set costs no redeploy. `edge-shared.test.ts` caught
 * exactly this mistake when `card-issues.ts` was first written.
 *
 * THREE CARDS CARRY NOTHING, DELIBERATELY.
 *   #11 Purple Dead Nettle — the printed back belongs to another plant (see
 *       `card-issues.ts`), so there is no claim on it worth sourcing until it is reprinted.
 *   #19 Sheep's Sorrel and #21 Chicory — held pending verification of the card backs.
 *
 * AND #38 WILLOW IS WHY THE "no two cards share a source" TEST EXISTS. The audit mapped
 * #38 to Cinquefoil (*Potentilla*), which is not what the deck prints: card #38 is Willow
 * (*Salix* spp.), whose own compounds are salicin/salicortin/tremulacin. Those three
 * Potentilla references were DISCARDED rather than reassigned — a citation attached to the
 * wrong plant is worse than no citation — and Willow's own three, checked separately,
 * took their place.
 *
 * A card with no entry here, or one whose evidence is `hold` or `exclude`, cites the deck
 * alone and shows no evidence label — silence, rather than a grade the audit declined to
 * give.
 */

/**
 * How well the audit found the card's own claims supported.
 *
 * `revise` is not a soft `mixed`: it means the audit found something the card states that
 * its evidence does not carry. The card cannot be corrected — every field is transcribed
 * from a printed card that is now in production — so the honest move is to say the card
 * needs review and record why in `docs/card-claim-review.md`.
 */
export type CardEvidence = 'strong' | 'mixed' | 'revise' | 'hold' | 'exclude';

export interface CardSources {
  evidence: CardEvidence;
  /** Ids in `src/data/sources.json`. Empty when the card is deliberately uncited. */
  sourceIds: string[];
  /** The audit's own verdict. Internal: it justifies the label, it is not shown. */
  auditNote: string;
}

/** Keyed by card number, as printed on the card. */
export const CARD_SOURCES: Record<string, CardSources> = {
  // #01 Dandelion
  '1': {
    evidence: 'strong',
    sourceIds: [
      'pmc-11764760',
      'pmc-10343869',
      'pmc-11434673',
    ],
    auditNote:
      'Good support for major constituents and several biological activities; keep human-health ' +
      'wording conservative.',
  },
  // #02 Broadleaf Dock
  '2': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-26384001',
      'pmc-9203642',
      'pubmed-30533432',
    ],
    auditNote:
      'Anthraquinones/tannins and traditional laxative/digestive uses are supportable; \'blood ' +
      'purification\' should be labeled traditional, not medical fact.',
  },
  // #03 Goldenrod
  '3': {
    evidence: 'strong',
    sourceIds: [
      'pmc-11244460',
      'pubmed-40284403',
      'pubmed-39795304',
    ],
    auditNote:
      'Good support for flavonoids, anti-inflammatory activity and traditional urinary/diuretic ' +
      'use.',
  },
  // #04 Ragweed
  '4': {
    evidence: 'revise',
    sourceIds: [
      'pubmed-35083849',
      'pubmed-36144651',
      'pubmed-33465625',
    ],
    auditNote:
      'Evidence does NOT strongly justify the card\'s fever, skin-care and digestive claims. Ragweed ' +
      'is also a major allergen. Reword as traditional/preclinical or revise the card.',
  },
  // #05 Lamb's Quarters
  '5': {
    evidence: 'strong',
    sourceIds: [
      'pmc-10343354',
      'pmc-4486584',
      'pubmed-9527345',
    ],
    auditNote:
      'Strong support for nutrient/mineral/vitamin content; medicinal skin/digestive claims are ' +
      'less established.',
  },
  // #06 Purslane
  '6': {
    evidence: 'strong',
    sourceIds: [
      'pubmed-28495602',
      'pubmed-25692148',
      'pubmed-37739100',
    ],
    auditNote:
      'Strong support for omega-3/nutrient profile and extensive preclinical pharmacology.',
  },
  // #07 Garlic Mustard
  '7': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-25308480',
      'pmc-4628127',
      'pmc-11354652',
    ],
    auditNote:
      'Sinigrin/glucosinolates are well supported. Broad \'detoxifying/diuretic/digestive\' claims ' +
      'are not well established specifically for A. petiolata.',
  },
  // #08 Stinging Nettle
  '8': {
    evidence: 'strong',
    sourceIds: [
      'pmc-8894011',
      'pmc-10176313',
      'nccih-bph-science-review',
    ],
    auditNote:
      'Good evidence base, but allergy/joint/circulatory claims vary in strength by preparation and ' +
      'indication.',
  },
  // #09 Wood Sorrel
  '9': {
    evidence: 'revise',
    sourceIds: [
      'kew-mpns-oxalis-stricta',
      'pubmed-34391377',
      'ouci-9gmm3z1e',
    ],
    auditNote:
      'Direct research on O. stricta is sparse. Vitamin C/oxalate and edible use are easier to ' +
      'support than digestive, appetite and diuretic claims. Avoid extrapolating other Oxalis ' +
      'species as proof.',
  },
  // #10 Red Clover
  '10': {
    evidence: 'mixed',
    sourceIds: [
      'nccih-red-clover',
      'ncbi-bookshelf-nbk74871',
      'pubmed-11528359',
    ],
    auditNote:
      'Isoflavones and estrogen-like activity are well supported; clinical benefits are ' +
      'inconsistent, so use \'studied for menopausal symptoms\' rather than \'hormone support\' as a ' +
      'proven effect.',
  },
  // #11 Purple Dead Nettle
  '11': {
    evidence: 'exclude',
    sourceIds: [],
    auditNote:
      'IGNORE FOR NOW: the card back in the current PDF is the wrong back. Do not source, display ' +
      'citations for, or revise this plant from this PDF.',
  },
  // #12 Wild Violet
  '12': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-35866842',
      'pmc-10630019',
      'pubmed-28948657',
    ],
    auditNote:
      'Genus-level support exists for flavonoids, mucilage, anthocyanins, vitamin C and ' +
      'respiratory/skin traditional use, but the evidence is not specific enough to claim all ' +
      'effects for V. sororia as proven.',
  },
  // #13 Chickweed
  '13': {
    evidence: 'strong',
    sourceIds: [
      'pubmed-32548330',
      'pubmed-39620022',
      'pubmed-37869918',
    ],
    auditNote:
      'Good support for phytochemicals and traditional topical use; \'laxative\' and \'itch relief\' ' +
      'should be framed as traditional rather than clinical.',
  },
  // #14 Broad Leaf Plantain
  '14': {
    evidence: 'strong',
    sourceIds: [
      'pubmed-29629064',
      'pubmed-10904143',
      'pmc-12348216',
    ],
    auditNote:
      'Good support for aucubin, mucilage, wound-related and antimicrobial/anti-inflammatory ' +
      'activity.',
  },
  // #15 Cleavers
  '15': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-42075201',
      'pubmed-39044256',
      'pubmed-31775336',
    ],
    auditNote:
      'Iridoids/flavonoids and some bioactivities are supported. \'Lymphatic support\', \'detoxifying\' ' +
      'and \'blood purification\' are traditional-herbal concepts, not established clinical outcomes.',
  },
  // #16 Ground Ivy
  '16': {
    evidence: 'mixed',
    sourceIds: [
      'pmc-9033597',
      'thieme-a-2866-3799',
      'pubmed-12490241',
    ],
    auditNote:
      'Traditional respiratory/digestive use exists, while many pharmacologic findings are ' +
      'preclinical. Phrase accordingly.',
  },
  // #17 Maple
  '17': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-34180070',
      'pmc-10469071',
      'pmc-9603788',
    ],
    auditNote:
      'Quebecol/phenolics are well supported mainly for maple syrup. \'Glucose regulation\' is mostly ' +
      'preclinical; avoid broad genus-wide medicinal claims.',
  },
  // #18 Blackberry
  '18': {
    evidence: 'strong',
    sourceIds: [
      'pubmed-22082199',
      'pubmed-34574260',
      'pubmed-26132562',
    ],
    auditNote:
      'Strong support for anthocyanins, ellagic acid, vitamin C and antioxidant profile; ' +
      'digestive/astringent uses are more traditional.',
  },
  // #19 Sheep's Sorrel
  '19': {
    evidence: 'hold',
    sourceIds: [],
    auditNote:
      'HOLD FOR VERIFICATION: this card is immediately adjacent to Sumac in the current deck and ' +
      'may have the wrong back. Do not source or revise it until the correct back is confirmed.',
  },
  // #20 Sumac
  '20': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-33430013',
      'pubmed-32042964',
      'pubmed-17909971',
    ],
    auditNote:
      'Strong evidence for tannins/gallic acid and preclinical antimicrobial/antidiabetic effects ' +
      'in some Rhus species. Do not imply every Rhus species is equivalent.',
  },
  // #21 Chicory
  '21': {
    evidence: 'hold',
    sourceIds: [],
    auditNote:
      'HOLD FOR VERIFICATION: this card is immediately adjacent to Sumac in the current deck and ' +
      'may have the wrong back. Do not source or revise it until the correct back is confirmed.',
  },
  // #22 Burdock
  '22': {
    evidence: 'strong',
    sourceIds: [
      'pubmed-36781057',
      'pubmed-34612502',
      'pubmed-29698388',
    ],
    auditNote:
      'Good phytochemical support, but effects vary greatly by root, fruit/seed and extract. Fix ' +
      'card typo: Arctium, not Articum.',
  },
  // #23 Wild Mint
  '23': {
    evidence: 'mixed',
    sourceIds: [
      'pmc-4171855',
      'pubmed-24100754',
      'pubmed-8805113',
    ],
    auditNote:
      'Menthol/menthone and digestive use are well established in Mentha/peppermint literature; ' +
      'headache/nausea evidence depends on species, route and preparation. Species-level labeling ' +
      'would improve credibility.',
  },
  // #24 Catnip
  '24': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-19041706',
      'pubmed-17439017',
      'pubmed-672466',
    ],
    auditNote:
      'Nepetalactone is well supported. Human calming/fever claims are largely traditional and not ' +
      'backed by robust clinical trials.',
  },
  // #25 Shepherd's Purse
  '25': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-39771011',
      'pubmed-28590768',
      'pubmed-29641247',
    ],
    auditNote:
      'Traditional hemostatic/menstrual use is documented, but do not present it as a substitute ' +
      'for medical care for abnormal bleeding.',
  },
  // #26 Self-Heal
  '26': {
    evidence: 'strong',
    sourceIds: [
      'pubmed-30864498',
      'pubmed-33538676',
      'pubmed-35814234',
    ],
    auditNote:
      'Strong preclinical support for rosmarinic/ursolic acids, flavonoids, antimicrobial and ' +
      'anti-inflammatory activity; clinical evidence remains limited.',
  },
  // #27 Mullein
  '27': {
    evidence: 'strong',
    sourceIds: [
      'pubmed-35088467',
      'sciencedirect-s0102695x13701261',
      'wiley-ptr-1653',
    ],
    auditNote:
      'Strong documentation of traditional respiratory use and mucilage/saponins/iridoids; clinical ' +
      'efficacy is less certain.',
  },
  // #28 Horsetail
  '28': {
    evidence: 'mixed',
    sourceIds: [
      'pmc-7954623',
      'pubmed-24723963',
      'pubmed-38615440',
    ],
    auditNote:
      'Diuretic evidence is relatively good. \'Bone support\' and \'keratin support\' are biologically ' +
      'plausible/silica-linked but not strongly established clinical outcomes.',
  },
  // #29 Field Garlic
  '29': {
    evidence: 'revise',
    sourceIds: [
      'pubmed-34420186',
      'pubmed-35170391',
      'pubmed-34567150',
    ],
    auditNote:
      'Quercetin/sulfur compounds fit Allium broadly, but \'allicin\' is especially associated with ' +
      'garlic and should not be generalized to all wild onions. Specify species or remove allicin.',
  },
  // #30 Wild Strawberry
  '30': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-40648036',
      'pubmed-27775146',
      'pubmed-24345049',
    ],
    auditNote:
      'Fruit vitamin C/phenolics are credible; oral-health/skin/digestive claims are more ' +
      'traditional and evidence often comes from other Fragaria species.',
  },
  // #31 Elderberry
  '31': {
    evidence: 'strong',
    sourceIds: [
      'pmc-7443157',
      'pmc-8026097',
      'pmc-13210375',
    ],
    auditNote:
      'One of the better-supported cards, but specify Sambucus nigra where clinical evidence is ' +
      'being cited and distinguish berry from other plant parts.',
  },
  // #32 St. John's Wort
  '32': {
    evidence: 'strong',
    sourceIds: [
      'pubmed-36246064',
      'pubmed-42302936',
      'pubmed-38600756',
    ],
    auditNote:
      'Strong evidence for mild-to-moderate depression in standardized extracts, plus significant ' +
      'drug-interaction risks. Wound/other effects have weaker evidence.',
  },
  // #33 Yarrow
  '33': {
    evidence: 'strong',
    sourceIds: [
      'pmc-9182061',
      'pmc-6313439',
      'pmc-12009018',
    ],
    auditNote:
      'Good support for traditional wound/fever use, flavonoids/volatile oils and anti-inflammatory ' +
      'activity. Some clinical wound data exist.',
  },
  // #34 Jewelweed
  '34': {
    evidence: 'revise',
    sourceIds: [
      'pubmed-9249283',
      'pmc-9659524',
      'pmc-11896621',
    ],
    auditNote:
      'Critical correction: a controlled trial found jewelweed extract was NOT effective for ' +
      'treating experimentally induced poison ivy/oak dermatitis. Do not market itch relief as ' +
      'established fact.',
  },
  // #35 Lemon Balm
  '35': {
    evidence: 'strong',
    sourceIds: [
      'pmc-12944213',
      'pmc-8998931',
      'pmc-11283336',
    ],
    auditNote:
      'Good support for rosmarinic acid/citral/citronellal and human anxiety/stress signals; ' +
      'antiviral/digestive findings are mainly preclinical/traditional.',
  },
  // #36 Bee Balm
  '36': {
    evidence: 'mixed',
    sourceIds: [
      'pmc-7659962',
      'pmc-8000036',
      'pubmed-41599385',
    ],
    auditNote:
      'Thymol/carvacrol and antimicrobial activity are plausible for several Monarda species, but ' +
      'composition varies widely. Specify species instead of \'Monarda spp.\' if possible.',
  },
  // #37 Wild Rose
  '37': {
    evidence: 'strong',
    sourceIds: [
      'pubmed-18384191',
      'pubmed-31138475',
      'pubmed-11933119',
    ],
    auditNote:
      'Strong support for rose-hip vitamin C/polyphenols and antioxidant activity; card generalizes ' +
      'from Rosa spp., so specify hips and species where possible.',
  },
  // #38 Willow
  '38': {
    evidence: 'strong',
    sourceIds: [
      'ema-salicis-cortex',
      'pubmed-37895439',
      'pubmed-19140170',
    ],
    auditNote:
      'Replaces the audit\'s original mapping, which was to Cinquefoil (Potentilla spp.) — a ' +
      'different family from the Willow (Salix spp.) the deck actually prints. Those three ' +
      'references were discarded rather than reassigned; these are Willow\'s own. EMA ' +
      'recognises well-established use of certain willow-bark dry extracts for short-term ' +
      'lower-back pain, and traditional use for minor joint pain and headache; a 2023 ' +
      'meta-analysis found significant pain relief in arthritis, and a systematic review ' +
      'found moderate evidence for ethanolic extract in low-back pain. Keep the claim to ' +
      'willow BARK and its preparations, not to every part of every Salix species.',
  },
  // #39 Wild Geranium
  '39': {
    evidence: 'mixed',
    sourceIds: [
      'pmc-10873751',
      'pubmed-1417694',
      'pmc-6259616',
    ],
    auditNote:
      'Tannins, gallic acid and astringent tradition are credible; direct clinical evidence for G. ' +
      'maculatum is sparse.',
  },
  // #40 Honeysuckle
  '40': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-35026509',
      'pmc-4519546',
      'pmc-7127058',
    ],
    auditNote:
      'Chlorogenic acid, flavonoids and preclinical antimicrobial/antiviral activity are supported ' +
      'in medicinal Lonicera species, especially L. japonica. Do not generalize all Lonicera ' +
      'species as interchangeable or edible.',
  },
  // #41 Pine
  '41': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-31424365',
      'pmc-8309100',
      'sciencedirect-003194229400885w',
    ],
    auditNote:
      'Pinene/terpenes and traditional respiratory use are credible, but Pinus spp. chemistry and ' +
      'edibility vary. Species identification is essential.',
  },
  // #42 Mulberry
  '42': {
    evidence: 'strong',
    sourceIds: [
      'pubmed-26850343',
      'pmc-9028580',
      'pubmed-34818743',
    ],
    auditNote:
      'Good support for anthocyanins/flavonoids and glucose-related effects, especially M. alba. ' +
      'Avoid implying identical effects across every Morus species/plant part.',
  },
  // #43 Passion Flower
  '43': {
    evidence: 'strong',
    sourceIds: [
      'pmc-7766837',
      'pubmed-18499602',
      'pubmed-11679026',
    ],
    auditNote:
      'Clinical evidence supports anxiety reduction signals. Harmine/harmaline content can be ' +
      'low/variable; avoid overstating them as defining active compounds without ' +
      'preparation-specific data.',
  },
  // #44 Prickly Lettuce
  '44': {
    evidence: 'mixed',
    sourceIds: [
      'pubmed-32235622',
      'pubmed-16621374',
      'pubmed-23662127',
    ],
    auditNote:
      'Lactucin/lactucopicrin and animal sedative/analgesic findings support the concept, but the ' +
      'card currently makes human \'pain relief/sleep\' sound much more established than it is.',
  },
  // #45 Oak
  '45': {
    evidence: 'strong',
    sourceIds: [
      'ema-quercus-cortex-assessment',
      'ema-quercus-cortex-references',
      'pmc-3834722',
    ],
    auditNote:
      'Strong traditional-use/monograph support for tannin-rich oak bark as an astringent and for ' +
      'minor skin/oral/GI uses. Specify bark species/preparation rather than all Quercus parts.',
  },
};

/**
 * The label a reader sees, or `null` where the audit reached no usable verdict.
 *
 * Written for someone holding a card rather than reading a methods section: it grades the
 * evidence behind the card, and never implies anything about whether a plant is safe.
 */
const EVIDENCE_LABEL: Partial<Record<CardEvidence, string>> = {
  strong: 'Well sourced',
  mixed: 'Evidence varies',
  revise: 'Card needs review',
};

function entryFor(herb: Herb): CardSources | undefined {
  return CARD_SOURCES[String(herb.cardNumber)];
}

/**
 * Everything that cites this plant as a whole: the card it was transcribed from, then the
 * independent references for it.
 *
 * The deck ref stays FIRST. It is the provenance of every field on the page, the curated
 * references are additional reading about the plant, and `sources.test.ts` pins the order
 * so a later refactor cannot quietly demote it.
 */
export function citationsFor(herb: Herb): SourceRef[] {
  const curated = entryFor(herb)?.sourceIds ?? [];
  return [...(herb.sources ?? []), ...curated.map((sourceId) => ({ sourceId }))];
}

/** The evidence label for this card, or `null` if it has none. */
export function evidenceLabelFor(herb: Herb): string | null {
  const entry = entryFor(herb);
  if (!entry || entry.sourceIds.length === 0) return null;
  return EVIDENCE_LABEL[entry.evidence] ?? null;
}

/** How many cards in the deck carry at least one independent reference. */
export function citedCardCount(): number {
  return DECK.herbs.filter((herb) => (entryFor(herb)?.sourceIds.length ?? 0) > 0).length;
}
