import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import { allSprites, hasSprite, spriteFor, SUPPORTED_FRAME_COUNTS } from './plant-sprites';
import { GROWTH_STAGES } from './garden';
import { isHerbId } from './deck';

/**
 * `public/cards/animated/` and `src/data/sprites.json` are both generated by
 * `scripts/build_sprites.py`, and nothing else in `npm run verify` reads either one —
 * the same blind spot the edge-function copies had. These tests are what catch a
 * manifest that points at a PNG nobody built, or a frame count the stylesheet has no
 * `steps()` class for (which would make the sprite slide instead of snap).
 */

const root = join(import.meta.dirname, '..', '..');

describe('plant sprite manifest', () => {
  it('has at least one authored portrait', () => {
    expect(allSprites().length).toBeGreaterThan(0);
  });

  it('only names real herbs from the deck', () => {
    for (const sprite of allSprites()) {
      expect(isHerbId(sprite.herbId), `${sprite.herbId} is not a deck herb`).toBe(true);
    }
  });

  it('points at a sheet that actually exists', () => {
    for (const sprite of allSprites()) {
      const path = join(root, 'public', sprite.src.replace(/^\//, ''));
      expect(existsSync(path), `${sprite.src} was never built`).toBe(true);
    }
  });

  it('uses a frame count the stylesheet can step through', () => {
    for (const sprite of allSprites()) {
      expect(SUPPORTED_FRAME_COUNTS).toContain(sprite.frames);
    }
  });

  it('declares a sheet wide enough for every frame it claims', () => {
    for (const sprite of allSprites()) {
      expect(sprite.frameWidth).toBeGreaterThan(0);
      expect(sprite.frameHeight).toBeGreaterThan(0);
      expect(sprite.fps).toBeGreaterThanOrEqual(6);
      // A handheld idle, not smooth animation — see the brief and build_sprites.py.
      expect(sprite.fps).toBeLessThanOrEqual(12);
    }
  });

  it('loops within three seconds', () => {
    for (const sprite of allSprites()) {
      const seconds = sprite.frames / sprite.fps;
      expect(seconds).toBeGreaterThanOrEqual(0.4);
      expect(seconds).toBeLessThanOrEqual(3);
    }
  });
});

describe('spriteFor', () => {
  it('returns null for a herb with no portrait yet, rather than throwing', () => {
    // Most of the deck has no sprite; pages mount the component unconditionally.
    expect(spriteFor('not-a-real-herb')).toBeNull();
    expect(hasSprite('not-a-real-herb')).toBe(false);
  });

  it('resolves every growth stage to real art', () => {
    const [first] = allSprites();
    for (const stage of GROWTH_STAGES) {
      const resolved = spriteFor(first!.herbId, stage);
      expect(resolved, `${stage} resolved to nothing`).not.toBeNull();
      expect(resolved!.frames).toBeGreaterThan(0);
    }
  });
});

describe('the stylesheet backs the manifest', () => {
  const css = readFileSync(join(root, 'src', 'app', 'globals.css'), 'utf8');

  it('has a steps() class for every frame count in use', () => {
    for (const sprite of allSprites()) {
      expect(css, `.plant-sprite-${sprite.frames} is missing`).toContain(
        `.plant-sprite-${sprite.frames} { animation-timing-function: steps(${sprite.frames}); }`,
      );
    }
  });

  // The global reduced-motion rule collapses animations to 0.01ms, which for a sprite
  // sheet means jumping to the end position — one whole sheet left — and vanishing.
  it('freezes sprites on frame 0 under reduced motion instead of collapsing them', () => {
    const block = css.slice(css.indexOf('@media (prefers-reduced-motion: reduce)'));
    expect(block).toContain('.plant-sprite {');
    expect(block).toContain('animation: none !important;');
    expect(block).toContain('background-position: 0 0 !important;');
  });

  it('renders pixels crisply, with no smoothing', () => {
    expect(css).toContain('image-rendering: pixelated');
  });
});
