import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import { allSprites, hasSprite, spriteFor, SUPPORTED_FRAME_COUNTS } from './plant-sprites';
import { GROWTH_STAGES } from './garden';
import { HERBS, isHerbId } from './deck';

/**
 * `public/cards/animated/` and `src/data/sprites.json` are both generated by
 * `scripts/build_sprites.py`, and nothing else in `npm run verify` reads either one —
 * the same blind spot the edge-function copies had. These tests are what catch a
 * manifest that points at a PNG nobody built, or a frame count the stylesheet has no
 * `steps()` class for (which would make the sprite slide instead of snap).
 */

const root = join(import.meta.dirname, '..', '..');

describe('plant sprite manifest', () => {
  it('has a portrait for every card in the deck', () => {
    // The set is complete, so this is the test that catches a herb added to the deck
    // without one - which would render a card with a hole where the creature goes.
    const missing = HERBS.filter((herb) => !hasSprite(herb.id)).map((herb) => herb.id);
    expect(missing, `no sprite authored for: ${missing.join(', ')}`).toEqual([]);
  });

  it('names a distinct personality for most of the deck', () => {
    // Not a style rule: the brief is that every species moves differently, and a
    // duplicated personality label is the cheapest available signal that two sprites
    // were authored to the same idea. A handful of overlaps is fine; a pile is not.
    const labels = allSprites().map((sprite) => sprite.personality);
    expect(new Set(labels).size).toBeGreaterThanOrEqual(labels.length - 3);
  });

  it('only names real herbs from the deck', () => {
    for (const sprite of allSprites()) {
      expect(isHerbId(sprite.herbId), `${sprite.herbId} is not a deck herb`).toBe(true);
    }
  });

  it('points at a sheet that actually exists', () => {
    for (const sprite of allSprites()) {
      const path = join(root, 'public', sprite.src.replace(/^\//, ''));
      expect(existsSync(path), `${sprite.src} was never built`).toBe(true);
    }
  });

  it('uses a frame count the stylesheet can step through', () => {
    for (const sprite of allSprites()) {
      expect(SUPPORTED_FRAME_COUNTS).toContain(sprite.frames);
    }
  });

  it('declares a sheet wide enough for every frame it claims', () => {
    for (const sprite of allSprites()) {
      expect(sprite.frameWidth).toBeGreaterThan(0);
      expect(sprite.frameHeight).toBeGreaterThan(0);
      expect(sprite.fps).toBeGreaterThanOrEqual(6);
      // A handheld idle, not smooth animation — see the brief and build_sprites.py.
      expect(sprite.fps).toBeLessThanOrEqual(12);
    }
  });

  it('loops within three seconds', () => {
    for (const sprite of allSprites()) {
      const seconds = sprite.frames / sprite.fps;
      expect(seconds).toBeGreaterThanOrEqual(0.4);
      expect(seconds).toBeLessThanOrEqual(3);
    }
  });
});

describe('spriteFor', () => {
  it('returns null for a herb with no portrait yet, rather than throwing', () => {
    // Most of the deck has no sprite; pages mount the component unconditionally.
    expect(spriteFor('not-a-real-herb')).toBeNull();
    expect(hasSprite('not-a-real-herb')).toBe(false);
  });

  it('resolves every growth stage to real art', () => {
    const [first] = allSprites();
    for (const stage of GROWTH_STAGES) {
      const resolved = spriteFor(first!.herbId, stage);
      expect(resolved, `${stage} resolved to nothing`).not.toBeNull();
      expect(resolved!.frames).toBeGreaterThan(0);
    }
  });
});

describe('the stylesheet backs the manifest', () => {
  const css = readFileSync(join(root, 'src', 'app', 'globals.css'), 'utf8');

  it('has a steps() class for every frame count in use', () => {
    for (const sprite of allSprites()) {
      expect(css, `.plant-sprite-${sprite.frames} is missing`).toContain(
        `.plant-sprite-${sprite.frames} { animation-timing-function: steps(${sprite.frames}); }`,
      );
    }
  });

  // The global reduced-motion rule collapses animations to 0.01ms, which for a sprite
  // sheet means jumping to the end position — one whole sheet left — and vanishing.
  it('freezes sprites on frame 0 under reduced motion instead of collapsing them', () => {
    const block = css.slice(css.indexOf('@media (prefers-reduced-motion: reduce)'));
    expect(block).toContain('.plant-sprite {');
    expect(block).toContain('animation: none !important;');
    expect(block).toContain('background-position: 0 0 !important;');
  });

  it('renders pixels crisply, with no smoothing', () => {
    expect(css).toContain('image-rendering: pixelated');
  });
});

describe('growth stages', () => {
  const staged = allSprites().flatMap((sprite) =>
    Object.entries(sprite.stages ?? {}).map(([stage, entry]) => ({
      herbId: sprite.herbId,
      stage,
      entry,
      adult: sprite,
    })),
  );

  it('stages every species in the deck, sprout and growing', () => {
    // Every assertion below iterates the staged set, so an empty one passes them all —
    // and now that the set is complete, this pins the completeness too. A species added
    // to the deck without stage art fails here rather than silently showing its adult
    // portrait at all three points of the ladder.
    expect(staged.length).toBeGreaterThan(0);
    for (const sprite of allSprites()) {
      expect(sprite.stages?.sprout, `${sprite.herbId}: no sprout stage`).toBeDefined();
      expect(sprite.stages?.growing, `${sprite.herbId}: no growing stage`).toBeDefined();
    }
  });

  it('ships the sheet each stage points at, and only for real stages', () => {
    for (const { herbId, stage, entry } of staged) {
      expect(GROWTH_STAGES, `${herbId}: unknown stage`).toContain(stage);
      expect(
        existsSync(join(root, 'public', entry.src)),
        `${herbId} (${stage}): ${entry.src} is in the manifest but not in public/`,
      ).toBe(true);
    }
  });

  it('uses a frame count the stylesheet can step through', () => {
    for (const { herbId, stage, entry } of staged) {
      expect(SUPPORTED_FRAME_COUNTS, `${herbId} (${stage})`).toContain(entry.frames);
    }
  });

  it('never has a single-frame stage', () => {
    // `--sprite-travel` is frames / (frames - 1), so one frame divides by zero and the
    // sprite disappears. SUPPORTED_FRAME_COUNTS rules it out today; this pins it.
    for (const { herbId, stage, entry } of staged) {
      expect(entry.frames, `${herbId} (${stage})`).toBeGreaterThan(1);
    }
  });

  it('shares one canvas with the adult it grows into', () => {
    // Stage art is drawn at evenly stepped heights INSIDE a shared frame. A stage with a
    // different frame box would break that scale silently — the plant would appear to
    // jump size for reasons unrelated to growth.
    for (const { herbId, stage, entry, adult } of staged) {
      expect(entry.frameWidth, `${herbId} (${stage}) width`).toBe(adult.frameWidth);
      expect(entry.frameHeight, `${herbId} (${stage}) height`).toBe(adult.frameHeight);
    }
  });

  it('speeds up as the plant grows', () => {
    // Speed is how strength reads. `build_sprites.py` enforces this too; this catches a
    // hand-edited manifest, which is the one path that skips the builder entirely.
    for (const sprite of allSprites()) {
      const stages = sprite.stages;
      if (!stages) continue;
      const rates = [stages.sprout?.fps, stages.growing?.fps, sprite.fps].filter(
        (fps): fps is number => fps !== undefined,
      );
      for (let i = 1; i < rates.length; i += 1) {
        expect(rates[i]!, `${sprite.herbId}: stage ${i} is not faster than the one before`)
          .toBeGreaterThan(rates[i - 1]!);
      }
      expect(Math.min(...rates)).toBeGreaterThanOrEqual(4);
    }
  });

  it('resolves every species to its own art at every stage', () => {
    // All 45 are staged, so there is no longer an unstaged species to exercise the
    // `?? entry` fallback in `spriteFor` — it stays because a species added to the deck
    // reaches the site before its stage art does, and rendering the adult beats
    // rendering nothing. What can still be pinned is that no lookup falls through by
    // accident: each stage must resolve to that stage's own sheet, not the adult's.
    for (const sprite of allSprites()) {
      expect(spriteFor(sprite.herbId, 'sprout')!.src).toBe(sprite.stages!.sprout!.src);
      expect(spriteFor(sprite.herbId, 'growing')!.src).toBe(sprite.stages!.growing!.src);
      expect(spriteFor(sprite.herbId, 'flowering')!.src).toBe(sprite.src);
    }
    expect(spriteFor('not-a-herb', 'sprout')).toBeNull();
  });
});

describe('the fitted sprite walk', () => {
  const css = readFileSync(join(root, 'src', 'app', 'globals.css'), 'utf8');

  it('declares the percentage keyframe a container-sized sprite animates with', () => {
    expect(css).toContain('@keyframes plant-sprite-play-fit');
    expect(css).toContain('background-position-x: var(--sprite-travel)');
  });

  it('declares .plant-sprite-fit AFTER .plant-sprite', () => {
    // Both are single-class selectors, so specificity ties and SOURCE ORDER decides which
    // `animation-name` wins. Declared first, the fitted walk loses to the pixel keyframe,
    // which then animates against an unset `--sprite-sheet-width` and walks the sheet
    // clean off the element — two of the four landing-page creatures simply vanished.
    const base = css.indexOf('\n.plant-sprite {');
    const fit = css.indexOf('\n.plant-sprite-fit {');
    expect(base, '.plant-sprite is missing').toBeGreaterThan(-1);
    expect(fit, '.plant-sprite-fit is missing').toBeGreaterThan(-1);
    expect(fit).toBeGreaterThan(base);
  });

  it('holds a fitted sprite on frame 0 under reduced motion', () => {
    const block = css.slice(css.indexOf('@media (prefers-reduced-motion: reduce)'));
    expect(block).toContain('.plant-sprite-fit {');
    expect(block).toContain('background-position-x: 0% !important;');
  });
});

describe('cache-busting versions', () => {
  const sheets = allSprites().flatMap((sprite) => [
    { label: sprite.herbId, entry: sprite },
    ...Object.entries(sprite.stages ?? {}).map(([stage, entry]) => ({
      label: `${sprite.herbId} (${stage})`,
      entry,
    })),
  ]);

  it('stamps every sheet with the hash of its actual bytes', () => {
    // THE FAILURE THIS CATCHES: a sprite redrawn and committed without re-running the
    // build, so the manifest still carries the old version. Every visitor holding the
    // previous art in cache then keeps it — the deploy succeeds and the site looks
    // unchanged, which is the least debuggable shape a bug can have. Recomputing the hash
    // here means a stale manifest fails `npm test` instead.
    for (const { label, entry } of sheets) {
      expect(entry.version, `${label} has no version`).toMatch(/^[0-9a-f]{8}$/);
      const bytes = readFileSync(join(root, 'public', entry.src));
      const actual = createHash('sha1').update(bytes).digest('hex').slice(0, 8);
      expect(entry.version, `${label}: manifest version is stale`).toBe(actual);
    }
  });

  it('gives different art different versions', () => {
    // Two sheets sharing a version would mean identical bytes, which for a deck whose
    // whole premise is that no two species look alike is a bug in itself.
    const byVersion = new Map<string, string>();
    for (const { label, entry } of sheets) {
      const clash = byVersion.get(entry.version);
      expect(clash, `${label} and ${clash} are byte-identical`).toBeUndefined();
      byVersion.set(entry.version, label);
    }
  });
});
