import manifest from '@/data/sprites.json';
import type { GardenStage } from './garden';

/**
 * Animated plant portraits — the lookup layer between a herb id and its sprite sheet.
 *
 * `sprites.json` is generated by `scripts/build_sprites.py` from the authored sources in
 * `scripts/sprite_sources/`; never hand-edit either it or the PNGs in
 * `public/cards/animated/`, for the same reason `herbs.json` is off limits.
 *
 * STAGES. `stage` is deliberately typed as the garden's own `GardenStage` rather than a
 * new vocabulary, because the growth ladder already exists and already maps one mastery
 * stage to exactly one growth stage (`src/lib/garden.ts`). All 45 species now carry a
 * `sprout` and a `growing` entry alongside their adult, so the creature a player sees
 * grows up with their own progress — see `docs/creature-stages.md` for what each stage
 * means botanically and `scripts/build_sprites.py` for how it is derived.
 *
 * COVERAGE. All 45 cards now have an authored portrait, and `plant-sprites.test.ts`
 * asserts that, so a herb added to the deck without one fails the suite rather than
 * silently rendering a card with a hole in it. `spriteFor` still returns null for an
 * unknown id — call sites mount the component unconditionally and an id that is not in
 * the deck at all should not throw.
 */

/**
 * Where frame 0's ink sits inside the frame, as fractions of the frame's own width and
 * height. Measured from the assembled sheet by `build_sprites.py`, never authored.
 */
export interface SpriteContentBox {
  left: number;
  top: number;
  right: number;
  bottom: number;
}

export interface PlantSpriteEntry {
  herbId: string;
  /** Site-root-relative path to the sheet; resolve through `assetPath()` before use. */
  src: string;
  /**
   * Short content hash of the sheet, appended to the URL as `?v=`.
   *
   * Sheets are regenerated in place — the filename never changes but the bytes do — and
   * `public/` is not fingerprinted by Next, so without this a browser holding the old art
   * keeps showing it after a deploy that redrew every portrait.
   */
  version: string;
  /** One frame's dimensions, already at the shipped scale. */
  frameWidth: number;
  frameHeight: number;
  frames: number;
  fps: number;
  /** Authored personality label, for documentation and tests rather than styling. */
  personality: string;
  /**
   * The resting pose's ink box. Optional in the type for the same reason `stages` is:
   * a manifest built before this field existed should render, not throw.
   */
  content?: SpriteContentBox;
  /**
   * Per-stage art. Present for every species in the deck; `plant-sprites.test.ts`
   * enforces that, so a species added without stage art fails the suite rather than
   * quietly showing its adult portrait at all three points of the ladder. Still
   * optional in the type, because a new species reaches the site before its stage art
   * does and rendering the adult beats rendering nothing.
   */
  stages?: Partial<Record<GardenStage, PlantSpriteEntry>>;
}

const SPRITES = manifest as Record<string, PlantSpriteEntry>;

/**
 * Frame counts the stylesheet has a `steps()` class for. `steps()` cannot read a CSS
 * custom property, so the count has to resolve to a literal in a class — this is the
 * list those classes cover, and `build_sprites.py` rejects anything outside it rather
 * than shipping a sheet that would slide smoothly instead of snapping frame to frame.
 */
export const SUPPORTED_FRAME_COUNTS = [4, 6, 8, 10, 12, 14, 16, 18] as const;

export function spriteFor(
  herbId: string,
  stage: GardenStage = 'flowering',
): PlantSpriteEntry | null {
  const entry = SPRITES[herbId];
  if (!entry) return null;
  // Falls back to the authored adult for a species whose stage art is not drawn yet.
  return entry.stages?.[stage] ?? entry;
}

export function hasSprite(herbId: string): boolean {
  return herbId in SPRITES;
}

/**
 * Whether this species has art drawn for this particular stage.
 *
 * Call sites need it to avoid scaling a sprite twice. Staged art is authored at evenly
 * stepped heights — 60%, 80%, 100% of the adult — so a caller that also shrinks a sprout
 * by its own factor compounds the two and lands at a quarter size. Every species is
 * staged today, so this returns true throughout; it stays for the same reason the
 * `stages` field is optional, since a species whose art has not been drawn yet still
 * needs an external scale if it is to show growth at all.
 */
export function hasStageArt(herbId: string, stage: GardenStage): boolean {
  return Boolean(SPRITES[herbId]?.stages?.[stage]);
}

/** How to scale and shift a fitted sprite so its plant, not its canvas, fills the frame. */
export interface SpriteContentFit {
  /** Multiplier on the sprite's own box. */
  scale: number;
  /** Translation as a percentage of the sprite's own (unscaled) width and height. */
  translateX: number;
  translateY: number;
}

/**
 * The share of a square frame a fitted plant may occupy.
 *
 * MEASURED, not chosen by eye: the badge's frame is a circle, so a plant sized to the
 * frame's full width would lose its corners to the curve. 0.74 is the largest value at
 * which not one of the deck's 135 sheets — 45 species times three growth stages — loses a
 * single pixel to that circle, at the tightest of the frame borders. 0.78 costs four
 * sprites a whisker, 0.82 costs twelve.
 *
 * `scripts/audit_sprites.py` re-measures that claim against the actual art, so a sprite
 * redrawn wider than the badge can hold fails the audit rather than shipping cropped.
 */
export const FRAME_FILL = 0.74;

/** A sprite drawn exactly as authored: no scale, no shift. */
const UNCHANGED: SpriteContentFit = { scale: 1, translateX: 0, translateY: 0 };

/**
 * Fit a sprite's PLANT to a square frame, rather than its canvas.
 *
 * Every stage of every species is drawn on the same canvas against a shared ground line,
 * so what changes as a plant grows is how much of the canvas it uses: a sprout's ink is
 * about 46% of the frame's height, an adult's about 82%. Rendered straight into a 36px
 * badge that means a seedling is roughly twelve pixels of plant inside a thirty-six pixel
 * circle — unreadable, and it reads as a sizing bug rather than as a young plant.
 *
 * This scales the plant up to the frame and re-centres it WITHOUT touching the art or the
 * stage: the badge still shows whichever sprite `stageForState` chose, and a sprout still
 * looks like a sprout — it is simply drawn at portrait size, the way a passport photograph
 * frames a face rather than a body.
 *
 * The scale is capped by BOTH dimensions and measured PER SPRITE, which is the whole
 * reason the manifest carries a box rather than this file carrying a per-stage constant:
 * a stage constant sized for the median sprout crops the widest one, and the deck's
 * sprouts range from 32% to 91% of the frame's width.
 *
 * `fill` is the share of the frame the ink box may occupy — see `FRAME_FILL`.
 */
export function contentFit(
  sprite: PlantSpriteEntry | null,
  fill = FRAME_FILL,
): SpriteContentFit {
  const box = sprite?.content;
  if (!sprite || !box) return UNCHANGED;

  const width = box.right - box.left;
  const height = box.bottom - box.top;
  if (!(width > 0) || !(height > 0)) return UNCHANGED;

  // The frame is wider than it is tall, and the sprite is sized by its width, so a
  // height budget spends `aspect` times as much of that width.
  const aspect = sprite.frameWidth / sprite.frameHeight;
  const scale = Math.min(fill / width, (fill * aspect) / height);

  // Centre of the ink, as a fraction of the frame. The sprite is centred in the frame
  // already, so the shift is whatever the ink's own centre is away from the middle —
  // scaled, because the transform scales about the sprite's centre before translating.
  const centreX = box.left + width / 2;
  const centreY = box.top + height / 2;

  return {
    scale,
    translateX: (0.5 - centreX) * scale * 100,
    translateY: (0.5 - centreY) * scale * 100,
  };
}

/** Every authored sprite, for tests and for tooling that needs the whole set. */
export function allSprites(): PlantSpriteEntry[] {
  return Object.values(SPRITES);
}
