import manifest from '@/data/sprites.json';
import type { GardenStage } from './garden';

/**
 * Animated plant portraits — the lookup layer between a herb id and its sprite sheet.
 *
 * `sprites.json` is generated by `scripts/build_sprites.py` from the authored sources in
 * `scripts/sprite_sources/`; never hand-edit either it or the PNGs in
 * `public/cards/animated/`, for the same reason `herbs.json` is off limits.
 *
 * STAGES. `stage` is deliberately typed as the garden's own `GardenStage` rather than a
 * new vocabulary, because the growth ladder already exists and already maps one mastery
 * stage to exactly one growth stage (`src/lib/garden.ts`). All 45 species now carry a
 * `sprout` and a `growing` entry alongside their adult, so the creature a player sees
 * grows up with their own progress — see `docs/creature-stages.md` for what each stage
 * means botanically and `scripts/build_sprites.py` for how it is derived.
 *
 * COVERAGE. All 45 cards now have an authored portrait, and `plant-sprites.test.ts`
 * asserts that, so a herb added to the deck without one fails the suite rather than
 * silently rendering a card with a hole in it. `spriteFor` still returns null for an
 * unknown id — call sites mount the component unconditionally and an id that is not in
 * the deck at all should not throw.
 */

export interface PlantSpriteEntry {
  herbId: string;
  /** Site-root-relative path to the sheet; resolve through `assetPath()` before use. */
  src: string;
  /**
   * Short content hash of the sheet, appended to the URL as `?v=`.
   *
   * Sheets are regenerated in place — the filename never changes but the bytes do — and
   * `public/` is not fingerprinted by Next, so without this a browser holding the old art
   * keeps showing it after a deploy that redrew every portrait.
   */
  version: string;
  /** One frame's dimensions, already at the shipped scale. */
  frameWidth: number;
  frameHeight: number;
  frames: number;
  fps: number;
  /** Authored personality label, for documentation and tests rather than styling. */
  personality: string;
  /**
   * Per-stage art. Present for every species in the deck; `plant-sprites.test.ts`
   * enforces that, so a species added without stage art fails the suite rather than
   * quietly showing its adult portrait at all three points of the ladder. Still
   * optional in the type, because a new species reaches the site before its stage art
   * does and rendering the adult beats rendering nothing.
   */
  stages?: Partial<Record<GardenStage, PlantSpriteEntry>>;
}

const SPRITES = manifest as Record<string, PlantSpriteEntry>;

/**
 * Frame counts the stylesheet has a `steps()` class for. `steps()` cannot read a CSS
 * custom property, so the count has to resolve to a literal in a class — this is the
 * list those classes cover, and `build_sprites.py` rejects anything outside it rather
 * than shipping a sheet that would slide smoothly instead of snapping frame to frame.
 */
export const SUPPORTED_FRAME_COUNTS = [4, 6, 8, 10, 12, 14, 16, 18] as const;

export function spriteFor(
  herbId: string,
  stage: GardenStage = 'flowering',
): PlantSpriteEntry | null {
  const entry = SPRITES[herbId];
  if (!entry) return null;
  // Falls back to the authored adult for a species whose stage art is not drawn yet.
  return entry.stages?.[stage] ?? entry;
}

export function hasSprite(herbId: string): boolean {
  return herbId in SPRITES;
}

/**
 * Whether this species has art drawn for this particular stage.
 *
 * Call sites need it to avoid scaling a sprite twice. Staged art is authored at evenly
 * stepped heights — 60%, 80%, 100% of the adult — so a caller that also shrinks a sprout
 * by its own factor compounds the two and lands at a quarter size. Every species is
 * staged today, so this returns true throughout; it stays for the same reason the
 * `stages` field is optional, since a species whose art has not been drawn yet still
 * needs an external scale if it is to show growth at all.
 */
export function hasStageArt(herbId: string, stage: GardenStage): boolean {
  return Boolean(SPRITES[herbId]?.stages?.[stage]);
}

/** Every authored sprite, for tests and for tooling that needs the whole set. */
export function allSprites(): PlantSpriteEntry[] {
  return Object.values(SPRITES);
}
