import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import type { PlantSpriteEntry } from './plant-sprites';
import {
  allSprites,
  contentFit,
  FRAME_FILL,
  hasSprite,
  spriteFor,
  SUPPORTED_FRAME_COUNTS,
} from './plant-sprites';
import { GROWTH_STAGES } from './garden';
import { HERBS, isHerbId } from './deck';

/**
 * `public/cards/animated/` and `src/data/sprites.json` are both generated by
 * `scripts/build_sprites.py`, and nothing else in `npm run verify` reads either one —
 * the same blind spot the edge-function copies had. These tests are what catch a
 * manifest that points at a PNG nobody built, or a frame count the stylesheet has no
 * `steps()` class for (which would make the sprite slide instead of snap).
 */

const root = join(import.meta.dirname, '..', '..');

describe('plant sprite manifest', () => {
  it('has a portrait for every card in the deck', () => {
    // The set is complete, so this is the test that catches a herb added to the deck
    // without one - which would render a card with a hole where the creature goes.
    const missing = HERBS.filter((herb) => !hasSprite(herb.id)).map((herb) => herb.id);
    expect(missing, `no sprite authored for: ${missing.join(', ')}`).toEqual([]);
  });

  it('names a distinct personality for most of the deck', () => {
    // Not a style rule: the brief is that every species moves differently, and a
    // duplicated personality label is the cheapest available signal that two sprites
    // were authored to the same idea. A handful of overlaps is fine; a pile is not.
    const labels = allSprites().map((sprite) => sprite.personality);
    expect(new Set(labels).size).toBeGreaterThanOrEqual(labels.length - 3);
  });

  it('only names real herbs from the deck', () => {
    for (const sprite of allSprites()) {
      expect(isHerbId(sprite.herbId), `${sprite.herbId} is not a deck herb`).toBe(true);
    }
  });

  it('points at a sheet that actually exists', () => {
    for (const sprite of allSprites()) {
      const path = join(root, 'public', sprite.src.replace(/^\//, ''));
      expect(existsSync(path), `${sprite.src} was never built`).toBe(true);
    }
  });

  it('uses a frame count the stylesheet can step through', () => {
    for (const sprite of allSprites()) {
      expect(SUPPORTED_FRAME_COUNTS).toContain(sprite.frames);
    }
  });

  it('declares a sheet wide enough for every frame it claims', () => {
    for (const sprite of allSprites()) {
      expect(sprite.frameWidth).toBeGreaterThan(0);
      expect(sprite.frameHeight).toBeGreaterThan(0);
      expect(sprite.fps).toBeGreaterThanOrEqual(6);
      // A handheld idle, not smooth animation — see the brief and build_sprites.py.
      expect(sprite.fps).toBeLessThanOrEqual(12);
    }
  });

  it('loops within three seconds', () => {
    for (const sprite of allSprites()) {
      const seconds = sprite.frames / sprite.fps;
      expect(seconds).toBeGreaterThanOrEqual(0.4);
      expect(seconds).toBeLessThanOrEqual(3);
    }
  });
});

describe('spriteFor', () => {
  it('returns null for a herb with no portrait yet, rather than throwing', () => {
    // Most of the deck has no sprite; pages mount the component unconditionally.
    expect(spriteFor('not-a-real-herb')).toBeNull();
    expect(hasSprite('not-a-real-herb')).toBe(false);
  });

  it('resolves every growth stage to real art', () => {
    const [first] = allSprites();
    for (const stage of GROWTH_STAGES) {
      const resolved = spriteFor(first!.herbId, stage);
      expect(resolved, `${stage} resolved to nothing`).not.toBeNull();
      expect(resolved!.frames).toBeGreaterThan(0);
    }
  });
});

describe('the stylesheet backs the manifest', () => {
  const css = readFileSync(join(root, 'src', 'app', 'globals.css'), 'utf8');

  it('has a steps() class for every frame count in use', () => {
    for (const sprite of allSprites()) {
      expect(css, `.plant-sprite-${sprite.frames} is missing`).toContain(
        `.plant-sprite-${sprite.frames} { animation-timing-function: steps(${sprite.frames}); }`,
      );
    }
  });

  // The global reduced-motion rule collapses animations to 0.01ms, which for a sprite
  // sheet means jumping to the end position — one whole sheet left — and vanishing.
  it('freezes sprites on frame 0 under reduced motion instead of collapsing them', () => {
    const block = css.slice(css.indexOf('@media (prefers-reduced-motion: reduce)'));
    expect(block).toContain('.plant-sprite {');
    expect(block).toContain('animation: none !important;');
    expect(block).toContain('background-position: 0 0 !important;');
  });

  it('renders pixels crisply, with no smoothing', () => {
    expect(css).toContain('image-rendering: pixelated');
  });
});

describe('growth stages', () => {
  const staged = allSprites().flatMap((sprite) =>
    Object.entries(sprite.stages ?? {}).map(([stage, entry]) => ({
      herbId: sprite.herbId,
      stage,
      entry,
      adult: sprite,
    })),
  );

  it('stages every species in the deck, sprout and growing', () => {
    // Every assertion below iterates the staged set, so an empty one passes them all —
    // and now that the set is complete, this pins the completeness too. A species added
    // to the deck without stage art fails here rather than silently showing its adult
    // portrait at all three points of the ladder.
    expect(staged.length).toBeGreaterThan(0);
    for (const sprite of allSprites()) {
      expect(sprite.stages?.sprout, `${sprite.herbId}: no sprout stage`).toBeDefined();
      expect(sprite.stages?.growing, `${sprite.herbId}: no growing stage`).toBeDefined();
    }
  });

  it('ships the sheet each stage points at, and only for real stages', () => {
    for (const { herbId, stage, entry } of staged) {
      expect(GROWTH_STAGES, `${herbId}: unknown stage`).toContain(stage);
      expect(
        existsSync(join(root, 'public', entry.src)),
        `${herbId} (${stage}): ${entry.src} is in the manifest but not in public/`,
      ).toBe(true);
    }
  });

  it('uses a frame count the stylesheet can step through', () => {
    for (const { herbId, stage, entry } of staged) {
      expect(SUPPORTED_FRAME_COUNTS, `${herbId} (${stage})`).toContain(entry.frames);
    }
  });

  it('never has a single-frame stage', () => {
    // `--sprite-travel` is frames / (frames - 1), so one frame divides by zero and the
    // sprite disappears. SUPPORTED_FRAME_COUNTS rules it out today; this pins it.
    for (const { herbId, stage, entry } of staged) {
      expect(entry.frames, `${herbId} (${stage})`).toBeGreaterThan(1);
    }
  });

  it('shares one canvas with the adult it grows into', () => {
    // Stage art is drawn at evenly stepped heights INSIDE a shared frame. A stage with a
    // different frame box would break that scale silently — the plant would appear to
    // jump size for reasons unrelated to growth.
    for (const { herbId, stage, entry, adult } of staged) {
      expect(entry.frameWidth, `${herbId} (${stage}) width`).toBe(adult.frameWidth);
      expect(entry.frameHeight, `${herbId} (${stage}) height`).toBe(adult.frameHeight);
    }
  });

  it('speeds up as the plant grows', () => {
    // Speed is how strength reads. `build_sprites.py` enforces this too; this catches a
    // hand-edited manifest, which is the one path that skips the builder entirely.
    for (const sprite of allSprites()) {
      const stages = sprite.stages;
      if (!stages) continue;
      const rates = [stages.sprout?.fps, stages.growing?.fps, sprite.fps].filter(
        (fps): fps is number => fps !== undefined,
      );
      for (let i = 1; i < rates.length; i += 1) {
        expect(rates[i]!, `${sprite.herbId}: stage ${i} is not faster than the one before`)
          .toBeGreaterThan(rates[i - 1]!);
      }
      expect(Math.min(...rates)).toBeGreaterThanOrEqual(4);
    }
  });

  it('resolves every species to its own art at every stage', () => {
    // All 45 are staged, so there is no longer an unstaged species to exercise the
    // `?? entry` fallback in `spriteFor` — it stays because a species added to the deck
    // reaches the site before its stage art does, and rendering the adult beats
    // rendering nothing. What can still be pinned is that no lookup falls through by
    // accident: each stage must resolve to that stage's own sheet, not the adult's.
    for (const sprite of allSprites()) {
      expect(spriteFor(sprite.herbId, 'sprout')!.src).toBe(sprite.stages!.sprout!.src);
      expect(spriteFor(sprite.herbId, 'growing')!.src).toBe(sprite.stages!.growing!.src);
      expect(spriteFor(sprite.herbId, 'flowering')!.src).toBe(sprite.src);
    }
    expect(spriteFor('not-a-herb', 'sprout')).toBeNull();
  });
});

describe('the fitted sprite walk', () => {
  const css = readFileSync(join(root, 'src', 'app', 'globals.css'), 'utf8');

  it('declares the percentage keyframe a container-sized sprite animates with', () => {
    expect(css).toContain('@keyframes plant-sprite-play-fit');
    expect(css).toContain('background-position-x: var(--sprite-travel)');
  });

  it('declares .plant-sprite-fit AFTER .plant-sprite', () => {
    // Both are single-class selectors, so specificity ties and SOURCE ORDER decides which
    // `animation-name` wins. Declared first, the fitted walk loses to the pixel keyframe,
    // which then animates against an unset `--sprite-sheet-width` and walks the sheet
    // clean off the element — two of the four landing-page creatures simply vanished.
    const base = css.indexOf('\n.plant-sprite {');
    const fit = css.indexOf('\n.plant-sprite-fit {');
    expect(base, '.plant-sprite is missing').toBeGreaterThan(-1);
    expect(fit, '.plant-sprite-fit is missing').toBeGreaterThan(-1);
    expect(fit).toBeGreaterThan(base);
  });

  it('holds a fitted sprite on frame 0 under reduced motion', () => {
    const block = css.slice(css.indexOf('@media (prefers-reduced-motion: reduce)'));
    expect(block).toContain('.plant-sprite-fit {');
    expect(block).toContain('background-position-x: 0% !important;');
  });
});

describe('cache-busting versions', () => {
  const sheets = allSprites().flatMap((sprite) => [
    { label: sprite.herbId, entry: sprite },
    ...Object.entries(sprite.stages ?? {}).map(([stage, entry]) => ({
      label: `${sprite.herbId} (${stage})`,
      entry,
    })),
  ]);

  it('stamps every sheet with the hash of its actual bytes', () => {
    // THE FAILURE THIS CATCHES: a sprite redrawn and committed without re-running the
    // build, so the manifest still carries the old version. Every visitor holding the
    // previous art in cache then keeps it — the deploy succeeds and the site looks
    // unchanged, which is the least debuggable shape a bug can have. Recomputing the hash
    // here means a stale manifest fails `npm test` instead.
    for (const { label, entry } of sheets) {
      expect(entry.version, `${label} has no version`).toMatch(/^[0-9a-f]{8}$/);
      const bytes = readFileSync(join(root, 'public', entry.src));
      const actual = createHash('sha1').update(bytes).digest('hex').slice(0, 8);
      expect(entry.version, `${label}: manifest version is stale`).toBe(actual);
    }
  });

  it('gives different art different versions', () => {
    // Two sheets sharing a version would mean identical bytes, which for a deck whose
    // whole premise is that no two species look alike is a bug in itself.
    const byVersion = new Map<string, string>();
    for (const { label, entry } of sheets) {
      const clash = byVersion.get(entry.version);
      expect(clash, `${label} and ${clash} are byte-identical`).toBeUndefined();
      byVersion.set(entry.version, label);
    }
  });
});

describe('the measured content box', () => {
  // Both halves of the manifest: the adult portraits and every staged sheet, since the
  // badge shows whichever stage the collection has earned.
  const entries = allSprites().flatMap((sprite) => [
    { label: sprite.herbId, entry: sprite },
    ...GROWTH_STAGES.filter((stage) => sprite.stages?.[stage]).map((stage) => ({
      label: `${sprite.herbId} (${stage})`,
      entry: sprite.stages![stage]!,
    })),
  ]);

  it('measures every sheet, adult and staged', () => {
    // Without this, a sprite built before the field existed silently falls back to the
    // unfitted rendering and is the one plant in the deck that looks wrong in the badge.
    for (const { label, entry } of entries) {
      const box = entry.content;
      expect(box, `${label} carries no content box`).toBeDefined();
      expect(box!.right, `${label}: empty ink box`).toBeGreaterThan(box!.left);
      expect(box!.bottom, `${label}: empty ink box`).toBeGreaterThan(box!.top);
      expect(box!.left).toBeGreaterThanOrEqual(0);
      expect(box!.top).toBeGreaterThanOrEqual(0);
      expect(box!.right).toBeLessThanOrEqual(1);
      expect(box!.bottom).toBeLessThanOrEqual(1);
    }
  });

  it('grows as the plant does, on one shared ground line', () => {
    // The reason the badge needed fitting at all, stated as a fact about the art: stages
    // share a canvas and a ground line, and only the top of the ink moves. If that ever
    // stopped being true the fit would be re-centring against an assumption.
    for (const sprite of allSprites()) {
      const sprout = sprite.stages?.sprout?.content;
      const growing = sprite.stages?.growing?.content;
      const adult = sprite.content;
      if (!sprout || !growing || !adult) continue;
      const height = (box: { top: number; bottom: number }) => box.bottom - box.top;
      expect(height(sprout), `${sprite.herbId}: sprout is not shorter than growing`).toBeLessThan(
        height(growing),
      );
      expect(height(growing), `${sprite.herbId}: growing is not shorter than adult`).toBeLessThan(
        height(adult),
      );
    }
  });
});

describe('contentFit', () => {
  const FILL = FRAME_FILL;
  const entries = allSprites().flatMap((sprite) =>
    [undefined, ...GROWTH_STAGES].map((stage) => ({
      label: `${sprite.herbId} (${stage ?? 'adult'})`,
      entry: stage ? spriteFor(sprite.herbId, stage)! : sprite,
    })),
  );

  it('never lets a plant outgrow the frame it is being fitted to', () => {
    // THE FAILURE THIS CATCHES, and the reason the scale is measured per sprite rather
    // than being one constant per stage: sprouts run from a third to nine tenths of the
    // frame's width, so a factor sized for the median crops the widest of them. The cap
    // has to hold in BOTH dimensions — a short, wide plant is limited by width and a
    // narrow, tall one by height.
    for (const { label, entry } of entries) {
      const box = entry.content!;
      const fit = contentFit(entry, FILL);
      const inkWidth = (box.right - box.left) * fit.scale;
      const inkHeight =
        ((box.bottom - box.top) * fit.scale * entry.frameHeight) / entry.frameWidth;
      expect(inkWidth, `${label} is drawn wider than the frame allows`).toBeLessThanOrEqual(
        FILL + 1e-9,
      );
      expect(inkHeight, `${label} is drawn taller than the frame allows`).toBeLessThanOrEqual(
        FILL + 1e-9,
      );
      // And it fills one of the two, or the plant is smaller than it needed to be.
      expect(Math.max(inkWidth, inkHeight), `${label} is fitted too small`).toBeCloseTo(FILL, 6);
    }
  });

  it('puts the plant in the middle of the frame', () => {
    // A sprout's ink sits low on its canvas, against the shared ground line. Scaling
    // alone would enlarge a plant that is still hugging the bottom of the badge.
    for (const { label, entry } of entries) {
      const box = entry.content!;
      const fit = contentFit(entry, FILL);
      // Where the ink's centre lands, as a fraction of the frame: the sprite is centred,
      // scaled about its own centre, then translated by the returned percentages.
      const centredX =
        0.5 + fit.scale * (box.left + (box.right - box.left) / 2 - 0.5) + fit.translateX / 100;
      const centredY =
        0.5 + fit.scale * (box.top + (box.bottom - box.top) / 2 - 0.5) + fit.translateY / 100;
      expect(centredX, `${label} is not horizontally centred`).toBeCloseTo(0.5, 6);
      expect(centredY, `${label} is not vertically centred`).toBeCloseTo(0.5, 6);
    }
  });

  it('gives a seedling the same room in the badge as the adult it grows into', () => {
    // THE PROBLEM THIS SOLVES. Unfitted, the badge drew the CANVAS at a flat share of the
    // frame, so how much plant you saw depended on how much of its canvas that stage
    // happened to use — and stages deliberately use different amounts. A seedling came out
    // around half the plant an adult did, in a 36px circle, which reads as a broken avatar
    // rather than as a young plant.
    //
    // Fitted, every stage of every species reaches the same share of the badge, so the
    // badge shows the stage the collection actually earned at a size that can be read.
    // The plant's larger dimension, as a share of the frame's width.
    const shown = (entry: PlantSpriteEntry, scale: number) => {
      const box = entry.content!;
      const aspect = entry.frameWidth / entry.frameHeight;
      return Math.max(
        (box.right - box.left) * scale,
        ((box.bottom - box.top) * scale) / aspect,
      );
    };

    const gaps: number[] = [];
    for (const sprite of allSprites()) {
      const sprout = spriteFor(sprite.herbId, 'sprout')!;
      expect(
        shown(sprout, contentFit(sprout).scale),
        `${sprite.herbId}: sprout is not fitted to the same share as its adult`,
      ).toBeCloseTo(shown(sprite, contentFit(sprite).scale), 6);
      // How tall the plant was drawn, unfitted, relative to its own adult. Height is the
      // dimension that collapses: stages share a ground line, so a young plant is a short
      // one, and at the flat share that shortness went straight into the badge.
      const height = (entry: PlantSpriteEntry) => entry.content!.bottom - entry.content!.top;
      gaps.push(height(sprout) / height(sprite));
    }

    // Not one species escaped it, which is why this is a fit rather than a nudge.
    for (const gap of gaps) expect(gap).toBeLessThan(0.7);
  });

  it('is what the sitewide badge renders with', () => {
    // The fit is worth nothing sitting in this file. `xs` is the badge; the larger
    // avatars deliberately keep the authored composition, ground line and all, so the
    // flat share has to survive alongside it rather than be replaced by it.
    const source = readFileSync(
      join(root, 'src', 'components', 'profile', 'ProfileAvatar.tsx'),
      'utf8',
    );
    expect(source, 'the badge no longer fits the plant to its frame').toMatch(
      /size === 'xs' \? contentFit\(/,
    );
    expect(source, 'the larger avatars lost their flat sprite width').toMatch(/w-\[\d+%\]/);
  });

  it('leaves a sprite alone when nothing was measured', () => {
    // A manifest built before the field existed, and the null a caller passes for "no
    // plant chosen". Neither may produce a NaN transform.
    expect(contentFit(null)).toEqual({ scale: 1, translateX: 0, translateY: 0 });
    const unmeasured = { ...allSprites()[0]!, content: undefined };
    expect(contentFit(unmeasured)).toEqual({ scale: 1, translateX: 0, translateY: 0 });
  });
});
