import type { ReactNode } from 'react';

/**
 * Skeletal formulas for the molecules the deck actually names.
 *
 * DO NOT EDIT THIS FILE. It is generated by `npm run build:structures`
 * (`scripts/chemistry/build_structures.py`); a hand-edit is overwritten by the next run.
 *
 * GENERATED GEOMETRY, HAND-CHECKED CHEMISTRY. The coordinates come from a real hexagon
 * lattice because a hand-placed benzene ring is never quite regular and a plate of wonky
 * rings reads as decoration rather than as chemistry. What is NOT generated is which atoms
 * go where: every entry below was checked against a reference before it shipped.
 *
 * A molecule is only listed here when it can be drawn BOTH accurately and legibly at the
 * size the plate renders it, and every entry was read back at that size before it shipped.
 * Rutin (quercetin plus a rutinose disaccharide) and taraxasterol (a pentacyclic
 * triterpene) are deliberately absent: at plate size they become a scribble, and a scribble
 * that claims to be a structure is worse than no structure at all — a reader cannot tell
 * the difference, so it spends the credibility the accurate ones earn. They render as the
 * pending plate instead, which says nothing untrue.
 *
 * Strokes are `currentColor`, so the plate's own violet carries through and there is no
 * colour decision made down here.
 */
export interface StructureArt {
  viewBox: string;
  art: ReactNode;
}

export const STRUCTURES: Record<string, StructureArt> = {
  'menthol': {
    viewBox: '-75.2 -67.0 129.3 105.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L0.0 -33.6" />
      <path d="M-19.1 -11.0L-38.1 -22.0" />
      <path d="M-38.1 -22.0L-59.2 -28.3" />
      <path d="M-38.1 -22.0L-44.4 -0.9" />
      <path d="M19.1 11.0L38.1 22.0" />
      <text x="0.0" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'menthone': {
    viewBox: '-75.2 -67.0 129.3 105.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L0.0 -36.2" />
      <path d="M3.4 -22.0L3.4 -36.2" />
      <path d="M-19.1 -11.0L-38.1 -22.0" />
      <path d="M-38.1 -22.0L-59.2 -28.3" />
      <path d="M-38.1 -22.0L-44.4 -0.9" />
      <path d="M19.1 11.0L38.1 22.0" />
      <text x="0.0" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'limonene': {
    viewBox: '-37.6 -60.0 72.6 141.6',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L0.0 -44.0" />
      <path d="M-0.0 22.0L-0.0 44.0" />
      <path d="M-0.0 44.0L-21.6 48.3" />
      <path d="M-0.0 44.0L4.3 65.6" />
      <path d="M-3.3 44.7L1.0 66.2" />
      </>
    ),
  },
  'thymol': {
    viewBox: '-73.2 -67.0 127.3 105.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L0.0 -33.6" />
      <path d="M-19.1 -11.0L-38.1 -22.0" />
      <path d="M-38.1 -22.0L-38.1 -44.1" />
      <path d="M-38.1 -22.0L-57.2 -10.9" />
      <path d="M19.1 11.0L38.1 22.0" />
      <text x="0.0" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'carvacrol': {
    viewBox: '-54.1 -67.0 127.3 127.1',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L0.0 -33.6" />
      <path d="M-19.1 -11.0L-38.1 -22.0" />
      <path d="M19.1 11.0L38.1 22.0" />
      <path d="M38.1 22.0L38.1 44.1" />
      <path d="M38.1 22.0L57.2 10.9" />
      <text x="0.0" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'gallic-acid': {
    viewBox: '-62.1 -78.0 124.2 142.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M-19.1 11.0L-29.1 16.8" />
      <path d="M-0.0 22.0L-0.0 33.6" />
      <path d="M19.1 11.0L29.1 16.8" />
      <path d="M0.0 -22.0L0.0 -44.0" />
      <path d="M0.0 -44.0L12.4 -51.1" />
      <path d="M1.7 -41.1L14.1 -48.2" />
      <path d="M0.0 -44.0L-10.1 -49.8" />
      <text x="-38.1" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-0.0" y="44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="38.1" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="19.1" y="-55.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-19.1" y="-55.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">HO</text>
      </>
    ),
  },
  'tyramine': {
    viewBox: '-64.2 -67.0 99.3 138.3',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L0.0 -33.6" />
      <path d="M-0.0 22.0L-0.0 44.0" />
      <path d="M-0.0 44.0L-18.9 55.3" />
      <path d="M-18.9 55.3L-27.4 50.2" />
      <text x="0.0" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-37.7" y="44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">NH2</text>
      </>
    ),
  },
  'oxalic-acid': {
    viewBox: '-35.0 -42.1 92.0 81.3',
    art: (
      <>
      <path d="M0.0 0.0L22.0 0.0" />
      <path d="M0.0 0.0L-7.1 -12.4" />
      <path d="M2.9 -1.7L-4.2 -14.1" />
      <path d="M0.0 0.0L-5.8 10.1" />
      <path d="M22.0 0.0L29.1 -12.4" />
      <path d="M24.9 1.7L32.1 -10.7" />
      <path d="M22.0 0.0L27.8 10.1" />
      <text x="-11.0" y="-19.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-11.0" y="19.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="33.0" y="-19.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="33.0" y="19.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'fumaric-acid': {
    viewBox: '-62.3 -56.0 143.7 98.0',
    art: (
      <>
      <path d="M0.0 0.0L19.1 -11.0" />
      <path d="M1.7 2.9L20.8 -8.1" />
      <path d="M0.0 0.0L-19.1 -11.0" />
      <path d="M19.1 -11.0L38.3 0.0" />
      <path d="M-19.1 -11.0L-19.1 -25.2" />
      <path d="M-15.7 -11.0L-15.7 -25.2" />
      <path d="M-19.1 -11.0L-29.3 -5.2" />
      <path d="M38.3 0.0L38.3 14.2" />
      <path d="M34.9 0.0L34.9 14.2" />
      <path d="M38.3 0.0L48.4 -5.8" />
      <text x="-19.1" y="-33.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-38.3" y="0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">HO</text>
      <text x="38.3" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="57.4" y="-11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'choline': {
    viewBox: '-38.0 -38.0 119.4 69.0',
    art: (
      <>
      <path d="M-9.7 -3.9L-22.0 -8.8" />
      <path d="M-2.0 -10.2L-4.4 -22.0" />
      <path d="M-8.9 5.4L-22.0 13.2" />
      <path d="M9.0 5.2L19.1 11.0" />
      <path d="M19.1 11.0L38.3 0.0" />
      <path d="M38.3 0.0L48.4 5.8" />
      <text x="0.0" y="0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">N+</text>
      <text x="57.4" y="11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'histamine': {
    viewBox: '-39.3 -68.0 103.5 103.2',
    art: (
      <>
      <path d="M0.0 -18.7L-11.5 -10.4" />
      <path d="M-15.4 1.6L-11.0 15.1" />
      <path d="M-10.0 2.7L-8.4 9.5" />
      <path d="M-11.0 15.1L0.6 15.1" />
      <path d="M14.2 5.2L17.8 -5.8" />
      <path d="M10.1 2.3L12.5 -3.0" />
      <path d="M17.8 -5.8L0.0 -18.7" />
      <path d="M0.0 -18.7L0.0 -40.7" />
      <path d="M0.0 -40.7L18.9 -52.0" />
      <path d="M18.9 -52.0L27.4 -46.9" />
      <text x="-17.8" y="-5.8" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">N</text>
      <text x="11.0" y="15.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">NH</text>
      <text x="37.7" y="-40.7" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">NH2</text>
      </>
    ),
  },
  'ascorbic-acid': {
    viewBox: '-60.2 -68.6 142.1 124.4',
    art: (
      <>
      <path d="M-6.3 -14.1L-17.8 -5.8" />
      <path d="M-17.8 -5.8L-11.0 15.1" />
      <path d="M-11.0 15.1L11.0 15.1" />
      <path d="M11.0 15.1L17.8 -5.8" />
      <path d="M17.8 -5.8L6.3 -14.1" />
      <path d="M-11.0 15.1L11.0 15.1" />
      <path d="M-5.5 11.1L5.5 11.1" />
      <path d="M-17.8 -5.8L-31.3 -10.2" />
      <path d="M-16.7 -9.0L-30.3 -13.4" />
      <path d="M-11.0 15.1L-14.9 26.0" />
      <path d="M11.0 15.1L14.9 26.0" />
      <path d="M17.8 -5.8L38.7 -12.6" />
      <path d="M38.7 -12.6L48.8 -18.4" />
      <path d="M38.7 -12.6L38.7 -34.6" />
      <path d="M38.7 -34.6L28.6 -40.4" />
      <text x="0.0" y="-18.7" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-38.7" y="-12.6" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-18.5" y="35.8" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="18.5" y="35.8" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="57.9" y="-23.6" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="19.6" y="-45.6" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">HO</text>
      </>
    ),
  },
  'allantoin': {
    viewBox: '-45.4 -63.7 136.7 146.8',
    art: (
      <>
      <path d="M0.0 -18.7L-9.4 -11.9" />
      <path d="M-14.6 4.1L-11.0 15.1" />
      <path d="M-11.0 15.1L11.0 15.1" />
      <path d="M11.0 15.1L14.6 4.1" />
      <path d="M9.4 -11.9L0.0 -18.7" />
      <path d="M0.0 -18.7L0.0 -32.9" />
      <path d="M3.4 -18.7L3.4 -32.9" />
      <path d="M-11.0 15.1L-19.3 26.6" />
      <path d="M-13.8 13.1L-22.1 24.6" />
      <path d="M11.0 15.1L17.8 24.5" />
      <path d="M33.6 36.8L44.4 41.1" />
      <path d="M44.4 41.1L44.4 55.3" />
      <path d="M41.0 41.1L41.0 55.3" />
      <path d="M44.4 41.1L53.5 37.4" />
      <text x="-17.8" y="-5.8" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">NH</text>
      <text x="17.8" y="-5.8" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">HN</text>
      <text x="0.0" y="-40.7" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-23.9" y="32.9" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="23.9" y="32.9" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">NH</text>
      <text x="44.4" y="63.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="64.8" y="32.9" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">NH2</text>
      </>
    ),
  },
  'quercetin': {
    viewBox: '-138.3 -111.0 200.4 153.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -55.0L-38.1 -44.0" />
      <path d="M-38.1 -44.0L-38.1 -29.8" />
      <path d="M-31.4 -18.1L-19.1 -11.0" />
      <path d="M-0.0 -22.0L-0.0 -44.0" />
      <path d="M-0.0 -44.0L-19.1 -55.0" />
      <path d="M-38.1 -44.0L-0.0 -44.0" />
      <path d="M-29.1 -41.5L-9.0 -41.5" />
      <path d="M-19.1 -55.0L-19.1 -69.2" />
      <path d="M-15.7 -55.0L-15.7 -69.2" />
      <path d="M-0.0 -44.0L10.0 -49.8" />
      <path d="M-19.1 11.0L-29.1 16.8" />
      <path d="M19.1 11.0L29.1 16.8" />
      <path d="M-38.1 -44.0L-57.2 -55.0" />
      <path d="M-76.2 -88.0L-95.3 -77.0" />
      <path d="M-78.6 -81.6L-88.6 -75.9" />
      <path d="M-95.3 -77.0L-95.3 -55.0" />
      <path d="M-95.3 -55.0L-76.2 -44.0" />
      <path d="M-88.6 -56.1L-78.6 -50.4" />
      <path d="M-76.2 -44.0L-57.2 -55.0" />
      <path d="M-57.2 -55.0L-57.2 -77.0" />
      <path d="M-61.5 -60.2L-61.5 -71.8" />
      <path d="M-57.2 -77.0L-76.2 -88.0" />
      <path d="M-95.3 -77.0L-105.3 -82.8" />
      <path d="M-95.3 -55.0L-105.3 -49.2" />
      <text x="-38.1" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-19.1" y="-77.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="19.1" y="-55.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-38.1" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="38.1" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-114.3" y="-88.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-114.3" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'kaempferol': {
    viewBox: '-138.3 -111.0 200.4 153.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -55.0L-38.1 -44.0" />
      <path d="M-38.1 -44.0L-38.1 -29.8" />
      <path d="M-31.4 -18.1L-19.1 -11.0" />
      <path d="M-0.0 -22.0L-0.0 -44.0" />
      <path d="M-0.0 -44.0L-19.1 -55.0" />
      <path d="M-38.1 -44.0L-0.0 -44.0" />
      <path d="M-29.1 -41.5L-9.0 -41.5" />
      <path d="M-19.1 -55.0L-19.1 -69.2" />
      <path d="M-15.7 -55.0L-15.7 -69.2" />
      <path d="M-0.0 -44.0L10.0 -49.8" />
      <path d="M-19.1 11.0L-29.1 16.8" />
      <path d="M19.1 11.0L29.1 16.8" />
      <path d="M-38.1 -44.0L-57.2 -55.0" />
      <path d="M-76.2 -88.0L-95.3 -77.0" />
      <path d="M-78.6 -81.6L-88.6 -75.9" />
      <path d="M-95.3 -77.0L-95.3 -55.0" />
      <path d="M-95.3 -55.0L-76.2 -44.0" />
      <path d="M-88.6 -56.1L-78.6 -50.4" />
      <path d="M-76.2 -44.0L-57.2 -55.0" />
      <path d="M-57.2 -55.0L-57.2 -77.0" />
      <path d="M-61.5 -60.2L-61.5 -71.8" />
      <path d="M-57.2 -77.0L-76.2 -88.0" />
      <path d="M-95.3 -77.0L-105.3 -82.8" />
      <text x="-38.1" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-19.1" y="-77.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="19.1" y="-55.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-38.1" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="38.1" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-114.3" y="-88.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'genistein': {
    viewBox: '-62.1 -111.0 162.3 153.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -55.0L-38.1 -44.0" />
      <path d="M-38.1 -44.0L-38.1 -29.8" />
      <path d="M-31.4 -18.1L-19.1 -11.0" />
      <path d="M-0.0 -22.0L-0.0 -44.0" />
      <path d="M-0.0 -44.0L-19.1 -55.0" />
      <path d="M-38.1 -44.0L-0.0 -44.0" />
      <path d="M-29.1 -41.5L-9.0 -41.5" />
      <path d="M-19.1 -55.0L-19.1 -69.2" />
      <path d="M-15.7 -55.0L-15.7 -69.2" />
      <path d="M-19.1 11.0L-29.1 16.8" />
      <path d="M19.1 11.0L29.1 16.8" />
      <path d="M-0.0 -44.0L19.1 -55.0" />
      <path d="M38.1 -88.0L19.1 -77.0" />
      <path d="M35.7 -81.6L25.7 -75.9" />
      <path d="M19.1 -77.0L19.1 -55.0" />
      <path d="M19.1 -55.0L38.1 -44.0" />
      <path d="M25.7 -56.1L35.7 -50.4" />
      <path d="M38.1 -44.0L57.2 -55.0" />
      <path d="M57.2 -55.0L57.2 -77.0" />
      <path d="M52.8 -60.2L52.8 -71.8" />
      <path d="M57.2 -77.0L38.1 -88.0" />
      <path d="M57.2 -77.0L67.2 -82.8" />
      <text x="-38.1" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-19.1" y="-77.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-38.1" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="38.1" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="76.2" y="-88.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'citronellal': {
    viewBox: '-40.6 -34.0 189.9 72.0',
    art: (
      <>
      <path d="M0.0 0.0L19.1 -11.0" />
      <path d="M19.1 -11.0L38.1 0.0" />
      <path d="M38.1 0.0L57.2 -11.0" />
      <path d="M57.2 -11.0L76.2 0.0" />
      <path d="M76.2 0.0L95.3 -11.0" />
      <path d="M95.3 -11.0L114.3 0.0" />
      <path d="M93.6 -8.1L112.6 2.9" />
      <path d="M114.3 0.0L133.4 -11.0" />
      <path d="M0.0 0.0L-12.3 -7.1" />
      <path d="M1.7 -2.9L-10.6 -10.0" />
      <path d="M38.1 0.0L38.1 22.0" />
      <path d="M114.3 0.0L114.3 22.0" />
      <text x="-19.1" y="-11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'lawsone': {
    viewBox: '-65.5 -99.2 131.0 134.3',
    art: (
      <>
      <path d="M22.0 0.0L11.0 -19.1" />
      <path d="M15.6 -2.4L9.9 -12.4" />
      <path d="M11.0 -19.1L-11.0 -19.1" />
      <path d="M-11.0 -19.1L-22.0 -0.0" />
      <path d="M-22.0 -0.0L-11.0 19.1" />
      <path d="M-15.6 2.4L-9.9 12.4" />
      <path d="M-11.0 19.1L11.0 19.1" />
      <path d="M11.0 19.1L22.0 0.0" />
      <path d="M11.0 -19.1L-11.0 -19.1" />
      <path d="M5.8 -14.7L-5.8 -14.7" />
      <path d="M22.0 -38.1L11.0 -57.2" />
      <path d="M11.0 -57.2L-11.0 -57.2" />
      <path d="M-11.0 -57.2L-22.0 -38.1" />
      <path d="M-22.0 -38.1L-11.0 -19.1" />
      <path d="M11.0 -19.1L22.0 -38.1" />
      <path d="M22.0 -38.1L36.2 -38.1" />
      <path d="M22.0 -34.7L36.2 -34.7" />
      <path d="M-22.0 -38.1L-36.2 -38.1" />
      <path d="M-22.0 -41.5L-36.2 -41.5" />
      <path d="M11.0 -57.2L-11.0 -57.2" />
      <path d="M5.8 -52.8L-5.8 -52.8" />
      <path d="M11.0 -57.2L16.8 -67.2" />
      <text x="44.0" y="-38.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-44.0" y="-38.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="22.0" y="-76.2" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'resveratrol': {
    viewBox: '-46.0 -61.1 215.2 119.2',
    art: (
      <>
      <path d="M22.0 0.0L11.0 -19.1" />
      <path d="M15.6 -2.4L9.9 -12.4" />
      <path d="M11.0 -19.1L-11.0 -19.1" />
      <path d="M-11.0 -19.1L-22.0 -0.0" />
      <path d="M-9.9 -12.4L-15.6 -2.4" />
      <path d="M-22.0 -0.0L-11.0 19.1" />
      <path d="M-11.0 19.1L11.0 19.1" />
      <path d="M-5.8 14.7L5.8 14.7" />
      <path d="M11.0 19.1L22.0 0.0" />
      <path d="M22.0 0.0L41.1 -11.0" />
      <path d="M41.1 -11.0L60.1 0.0" />
      <path d="M39.4 -8.1L58.4 2.9" />
      <path d="M60.1 0.0L79.2 -11.0" />
      <path d="M123.2 -11.0L112.2 -30.1" />
      <path d="M116.8 -13.4L111.0 -23.4" />
      <path d="M112.2 -30.1L90.2 -30.1" />
      <path d="M90.2 -30.1L79.2 -11.0" />
      <path d="M91.3 -23.4L85.5 -13.4" />
      <path d="M79.2 -11.0L90.2 8.1" />
      <path d="M90.2 8.1L112.2 8.1" />
      <path d="M95.4 3.7L106.9 3.7" />
      <path d="M112.2 8.1L123.2 -11.0" />
      <path d="M123.2 -11.0L134.8 -11.0" />
      <path d="M-11.0 -19.1L-16.8 -29.1" />
      <path d="M-11.0 19.1L-16.8 29.1" />
      <text x="145.2" y="-11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-22.0" y="-38.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-22.0" y="38.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'emodin': {
    viewBox: '-62.1 -67.0 192.4 131.0',
    art: (
      <>
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M19.1 -11.0L19.1 11.0" />
      <path d="M14.7 -5.8L14.7 5.8" />
      <path d="M95.3 -11.0L76.2 -22.0" />
      <path d="M88.6 -9.9L78.6 -15.6" />
      <path d="M76.2 -22.0L57.2 -11.0" />
      <path d="M57.2 -11.0L57.2 11.0" />
      <path d="M57.2 11.0L76.2 22.0" />
      <path d="M76.2 22.0L95.3 11.0" />
      <path d="M78.6 15.6L88.6 9.9" />
      <path d="M95.3 11.0L95.3 -11.0" />
      <path d="M57.2 -11.0L57.2 11.0" />
      <path d="M61.5 -5.8L61.5 5.8" />
      <path d="M57.2 -11.0L38.1 -22.0" />
      <path d="M38.1 -22.0L19.1 -11.0" />
      <path d="M19.1 11.0L38.1 22.0" />
      <path d="M38.1 22.0L57.2 11.0" />
      <path d="M38.1 -22.0L38.1 -36.2" />
      <path d="M41.5 -22.0L41.5 -36.2" />
      <path d="M38.1 22.0L38.1 36.2" />
      <path d="M34.7 22.0L34.7 36.2" />
      <path d="M0.0 -22.0L0.0 -33.6" />
      <path d="M-19.1 11.0L-29.1 16.8" />
      <path d="M76.2 -22.0L76.2 -33.6" />
      <path d="M95.3 11.0L114.3 22.0" />
      <text x="38.1" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="38.1" y="44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="0.0" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-38.1" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="76.2" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'rosmarinic-acid': {
    viewBox: '-68.0 -67.0 294.3 147.1',
    art: (
      <>
      <path d="M22.0 0.0L11.0 -19.1" />
      <path d="M15.6 -2.4L9.9 -12.4" />
      <path d="M11.0 -19.1L-11.0 -19.1" />
      <path d="M-11.0 -19.1L-22.0 -0.0" />
      <path d="M-9.9 -12.4L-15.6 -2.4" />
      <path d="M-22.0 -0.0L-11.0 19.1" />
      <path d="M-11.0 19.1L11.0 19.1" />
      <path d="M-5.8 14.7L5.8 14.7" />
      <path d="M11.0 19.1L22.0 0.0" />
      <path d="M-11.0 -19.1L-16.8 -29.1" />
      <path d="M-22.0 -0.0L-33.6 -0.0" />
      <path d="M22.0 0.0L41.1 -11.0" />
      <path d="M41.1 -11.0L60.1 0.0" />
      <path d="M39.4 -8.1L58.4 2.9" />
      <path d="M60.1 0.0L79.2 -11.0" />
      <path d="M79.2 -11.0L79.2 -25.2" />
      <path d="M82.6 -11.0L82.6 -25.2" />
      <path d="M79.2 -11.0L91.5 -3.9" />
      <path d="M105.0 -3.9L117.3 -11.0" />
      <path d="M117.3 -11.0L117.3 -33.0" />
      <path d="M117.3 -33.0L129.6 -40.1" />
      <path d="M119.0 -30.1L131.3 -37.2" />
      <path d="M117.3 -33.0L107.2 -38.8" />
      <path d="M117.3 -11.0L117.3 11.0" />
      <path d="M117.3 11.0L136.3 22.0" />
      <path d="M180.3 22.0L169.3 2.9" />
      <path d="M174.0 19.6L168.2 9.6" />
      <path d="M169.3 2.9L147.3 2.9" />
      <path d="M147.3 2.9L136.3 22.0" />
      <path d="M148.5 9.6L142.7 19.6" />
      <path d="M136.3 22.0L147.3 41.1" />
      <path d="M147.3 41.1L169.3 41.1" />
      <path d="M152.5 36.7L164.1 36.7" />
      <path d="M169.3 41.1L180.3 22.0" />
      <path d="M169.3 41.1L175.1 51.1" />
      <path d="M180.3 22.0L191.9 22.0" />
      <text x="-22.0" y="-38.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-44.0" y="-0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="79.2" y="-33.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="98.2" y="0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="136.3" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="98.2" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">HO</text>
      <text x="180.3" y="60.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="202.3" y="22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'harmine': {
    viewBox: '-79.7 -58.4 199.5 93.5',
    art: (
      <>
      <path d="M22.0 0.0L11.0 -19.1" />
      <path d="M11.0 -19.1L-11.0 -19.1" />
      <path d="M-11.0 -19.1L-22.0 -0.0" />
      <path d="M-9.9 -12.4L-15.6 -2.4" />
      <path d="M-22.0 -0.0L-11.0 19.1" />
      <path d="M-11.0 19.1L11.0 19.1" />
      <path d="M-5.8 14.7L5.8 14.7" />
      <path d="M11.0 19.1L22.0 0.0" />
      <path d="M22.0 0.0L11.0 -19.1" />
      <path d="M15.6 -2.4L9.9 -12.4" />
      <path d="M11.0 -19.1L18.8 -27.7" />
      <path d="M35.2 -31.2L45.8 -26.5" />
      <path d="M45.8 -26.5L43.5 -4.6" />
      <path d="M43.5 -4.6L22.0 -0.0" />
      <path d="M43.5 -4.6L22.0 -0.0" />
      <path d="M43.5 -4.6L61.3 8.4" />
      <path d="M61.3 8.4L74.3 2.6" />
      <path d="M82.2 -8.3L83.7 -22.5" />
      <path d="M83.7 -22.5L65.9 -35.4" />
      <path d="M65.9 -35.4L45.8 -26.5" />
      <path d="M65.9 -35.4L45.8 -26.5" />
      <path d="M43.5 -4.6L61.3 8.4" />
      <path d="M50.3 -5.0L59.6 1.8" />
      <path d="M82.2 -8.3L83.7 -22.5" />
      <path d="M77.7 -11.4L78.9 -18.7" />
      <path d="M83.7 -22.5L103.8 -31.4" />
      <path d="M-22.0 -0.0L-36.2 -0.0" />
      <path d="M-51.0 3.5L-63.7 9.8" />
      <text x="25.7" y="-35.4" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">HN</text>
      <text x="81.4" y="-0.6" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">N</text>
      <text x="-44.0" y="-0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'harmaline': {
    viewBox: '-79.7 -58.4 199.5 93.5',
    art: (
      <>
      <path d="M22.0 0.0L11.0 -19.1" />
      <path d="M11.0 -19.1L-11.0 -19.1" />
      <path d="M-11.0 -19.1L-22.0 -0.0" />
      <path d="M-9.9 -12.4L-15.6 -2.4" />
      <path d="M-22.0 -0.0L-11.0 19.1" />
      <path d="M-11.0 19.1L11.0 19.1" />
      <path d="M-5.8 14.7L5.8 14.7" />
      <path d="M11.0 19.1L22.0 0.0" />
      <path d="M22.0 0.0L11.0 -19.1" />
      <path d="M15.6 -2.4L9.9 -12.4" />
      <path d="M11.0 -19.1L18.8 -27.7" />
      <path d="M35.2 -31.2L45.8 -26.5" />
      <path d="M45.8 -26.5L43.5 -4.6" />
      <path d="M43.5 -4.6L22.0 -0.0" />
      <path d="M43.5 -4.6L22.0 -0.0" />
      <path d="M43.5 -4.6L61.3 8.4" />
      <path d="M61.3 8.4L74.3 2.6" />
      <path d="M82.2 -8.3L83.7 -22.5" />
      <path d="M83.7 -22.5L65.9 -35.4" />
      <path d="M65.9 -35.4L45.8 -26.5" />
      <path d="M65.9 -35.4L45.8 -26.5" />
      <path d="M61.3 8.4L74.3 2.6" />
      <path d="M63.4 2.6L70.0 -0.8" />
      <path d="M83.7 -22.5L103.8 -31.4" />
      <path d="M-22.0 -0.0L-36.2 -0.0" />
      <path d="M-51.0 3.5L-63.7 9.8" />
      <text x="25.7" y="-35.4" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">HN</text>
      <text x="81.4" y="-0.6" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">N</text>
      <text x="-44.0" y="-0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'azulene': {
    viewBox: '-63.7 -71.2 97.5 102.3',
    art: (
      <>
      <path d="M0.0 -18.7L-17.8 -5.8" />
      <path d="M-17.8 -5.8L-11.0 15.1" />
      <path d="M-11.0 15.1L11.0 15.1" />
      <path d="M11.0 15.1L17.8 -5.8" />
      <path d="M17.8 -5.8L0.0 -18.7" />
      <path d="M-17.8 -5.8L-39.0 -11.6" />
      <path d="M-39.0 -11.6L-47.7 -31.9" />
      <path d="M-47.7 -31.9L-37.2 -51.2" />
      <path d="M-37.2 -51.2L-15.6 -55.2" />
      <path d="M-15.6 -55.2L1.0 -40.7" />
      <path d="M1.0 -40.7L0.0 -18.7" />
      <path d="M1.0 -40.7L0.0 -18.7" />
      <path d="M-17.8 -5.8L-11.0 15.1" />
      <path d="M-12.2 -1.8L-8.9 8.6" />
      <path d="M11.0 15.1L17.8 -5.8" />
      <path d="M8.9 8.6L12.2 -1.8" />
      <path d="M-17.8 -5.8L-39.0 -11.6" />
      <path d="M-21.4 -11.5L-33.0 -14.6" />
      <path d="M-47.7 -31.9L-37.2 -51.2" />
      <path d="M-41.3 -34.1L-35.6 -44.7" />
      <path d="M-15.6 -55.2L1.0 -40.7" />
      <path d="M-14.8 -48.5L-5.7 -40.6" />
      </>
    ),
  },
  'salicin': {
    viewBox: '-38.0 -83.1 183.0 171.3',
    art: (
      <>
      <path d="M22.0 0.0L11.0 -19.1" />
      <path d="M15.6 -2.4L9.9 -12.4" />
      <path d="M11.0 -19.1L-11.0 -19.1" />
      <path d="M-11.0 -19.1L-22.0 -0.0" />
      <path d="M-9.9 -12.4L-15.6 -2.4" />
      <path d="M-22.0 -0.0L-11.0 19.1" />
      <path d="M-11.0 19.1L11.0 19.1" />
      <path d="M-5.8 14.7L5.8 14.7" />
      <path d="M11.0 19.1L22.0 0.0" />
      <path d="M11.0 -19.1L22.0 -38.1" />
      <path d="M22.0 -38.1L22.0 -49.7" />
      <path d="M22.0 0.0L36.2 0.0" />
      <path d="M99.0 11.0L88.0 -8.1" />
      <path d="M88.0 -8.1L66.0 -8.1" />
      <path d="M66.0 -8.1L55.0 11.0" />
      <path d="M55.0 11.0L62.1 23.3" />
      <path d="M73.8 30.1L88.0 30.1" />
      <path d="M88.0 30.1L99.0 11.0" />
      <path d="M88.0 30.1L99.0 49.1" />
      <path d="M99.0 49.1L93.2 59.2" />
      <path d="M99.0 11.0L110.6 11.0" />
      <path d="M88.0 -8.1L93.8 -18.1" />
      <path d="M66.0 -8.1L60.2 -18.1" />
      <path d="M49.5 5.5L55.0 11.0" />
      <text x="22.0" y="-60.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="44.0" y="0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="66.0" y="30.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="88.0" y="68.2" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="121.0" y="11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="99.0" y="-27.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="55.0" y="-27.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'chlorogenic-acid': {
    viewBox: '-68.0 -61.1 275.3 122.2',
    art: (
      <>
      <path d="M22.0 0.0L11.0 -19.1" />
      <path d="M15.6 -2.4L9.9 -12.4" />
      <path d="M11.0 -19.1L-11.0 -19.1" />
      <path d="M-11.0 -19.1L-22.0 -0.0" />
      <path d="M-9.9 -12.4L-15.6 -2.4" />
      <path d="M-22.0 -0.0L-11.0 19.1" />
      <path d="M-11.0 19.1L11.0 19.1" />
      <path d="M-5.8 14.7L5.8 14.7" />
      <path d="M11.0 19.1L22.0 0.0" />
      <path d="M-11.0 -19.1L-16.8 -29.1" />
      <path d="M-22.0 -0.0L-33.6 -0.0" />
      <path d="M22.0 0.0L41.1 -11.0" />
      <path d="M41.1 -11.0L60.1 0.0" />
      <path d="M39.4 -8.1L58.4 2.9" />
      <path d="M60.1 0.0L79.2 -11.0" />
      <path d="M79.2 -11.0L79.2 -25.2" />
      <path d="M82.6 -11.0L82.6 -25.2" />
      <path d="M79.2 -11.0L91.5 -3.9" />
      <path d="M105.0 -3.9L117.3 -11.0" />
      <path d="M161.3 -11.0L150.3 -30.1" />
      <path d="M150.3 -30.1L128.3 -30.1" />
      <path d="M128.3 -30.1L117.3 -11.0" />
      <path d="M117.3 -11.0L128.3 8.1" />
      <path d="M128.3 8.1L150.3 8.1" />
      <path d="M150.3 8.1L161.3 -11.0" />
      <path d="M161.3 -11.0L172.9 -11.0" />
      <path d="M150.3 8.1L150.3 30.1" />
      <path d="M150.3 30.1L162.6 37.2" />
      <path d="M148.6 33.0L160.9 40.1" />
      <path d="M150.3 30.1L140.2 35.9" />
      <text x="-22.0" y="-38.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-44.0" y="-0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="79.2" y="-33.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="98.2" y="0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="183.3" y="-11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="169.3" y="41.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="131.2" y="41.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">HO</text>
      </>
    ),
  },
  'allicin': {
    viewBox: '-16.0 -45.0 146.3 65.0',
    art: (
      <>
      <path d="M0.0 0.0L19.1 -11.0" />
      <path d="M1.7 2.9L20.8 -8.1" />
      <path d="M19.1 -11.0L31.3 -3.9" />
      <path d="M44.9 -3.9L50.4 -7.1" />
      <path d="M63.9 -7.1L76.2 0.0" />
      <path d="M76.2 0.0L95.3 -11.0" />
      <path d="M95.3 -11.0L114.3 0.0" />
      <path d="M93.6 -8.1L112.6 2.9" />
      <path d="M38.1 -7.8L38.1 -14.2" />
      <path d="M41.5 -7.8L41.5 -14.2" />
      <text x="38.1" y="0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">S</text>
      <text x="57.2" y="-11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">S</text>
      <text x="38.1" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'flavonoid-core': {
    viewBox: '-111.3 -104.0 146.3 142.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -55.0L-38.1 -44.0" />
      <path d="M-38.1 -44.0L-38.1 -29.8" />
      <path d="M-31.4 -18.1L-19.1 -11.0" />
      <path d="M-0.0 -22.0L-0.0 -44.0" />
      <path d="M-0.0 -44.0L-19.1 -55.0" />
      <path d="M-38.1 -44.0L-19.1 -55.0" />
      <path d="M-31.4 -42.9L-21.4 -48.6" />
      <path d="M-38.1 -44.0L-57.2 -55.0" />
      <path d="M-76.2 -88.0L-95.3 -77.0" />
      <path d="M-78.6 -81.6L-88.6 -75.9" />
      <path d="M-95.3 -77.0L-95.3 -55.0" />
      <path d="M-95.3 -55.0L-76.2 -44.0" />
      <path d="M-88.6 -56.1L-78.6 -50.4" />
      <path d="M-76.2 -44.0L-57.2 -55.0" />
      <path d="M-57.2 -55.0L-57.2 -77.0" />
      <path d="M-61.5 -60.2L-61.5 -71.8" />
      <path d="M-57.2 -77.0L-76.2 -88.0" />
      <text x="-38.1" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'coumarin-core': {
    viewBox: '-78.7 -78.0 113.7 116.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -55.0L-38.1 -44.0" />
      <path d="M-38.1 -44.0L-38.1 -29.8" />
      <path d="M-31.4 -18.1L-19.1 -11.0" />
      <path d="M-0.0 -22.0L-0.0 -44.0" />
      <path d="M-0.0 -44.0L-19.1 -55.0" />
      <path d="M-38.1 -44.0L-50.4 -51.1" />
      <path d="M-36.4 -46.9L-48.7 -54.0" />
      <path d="M-19.1 -55.0L-0.0 -44.0" />
      <path d="M-16.7 -48.6L-6.7 -42.9" />
      <text x="-38.1" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-57.2" y="-55.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'iridoid-core': {
    viewBox: '-51.4 -45.0 86.5 106.8',
    art: (
      <>
      <path d="M19.1 -11.0L6.8 -18.1" />
      <path d="M-6.8 -18.1L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M-0.0 22.0L-4.6 43.5" />
      <path d="M-4.6 43.5L-26.5 45.8" />
      <path d="M-26.5 45.8L-35.4 25.7" />
      <path d="M-35.4 25.7L-19.1 11.0" />
      <path d="M-35.4 25.7L-19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <text x="0.0" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'anthraquinone-core': {
    viewBox: '-35.1 -67.0 146.3 131.0',
    art: (
      <>
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M19.1 -11.0L19.1 11.0" />
      <path d="M14.7 -5.8L14.7 5.8" />
      <path d="M95.3 -11.0L76.2 -22.0" />
      <path d="M88.6 -9.9L78.6 -15.6" />
      <path d="M76.2 -22.0L57.2 -11.0" />
      <path d="M57.2 -11.0L57.2 11.0" />
      <path d="M57.2 11.0L76.2 22.0" />
      <path d="M76.2 22.0L95.3 11.0" />
      <path d="M78.6 15.6L88.6 9.9" />
      <path d="M95.3 11.0L95.3 -11.0" />
      <path d="M57.2 -11.0L57.2 11.0" />
      <path d="M61.5 -5.8L61.5 5.8" />
      <path d="M57.2 -11.0L38.1 -22.0" />
      <path d="M38.1 -22.0L19.1 -11.0" />
      <path d="M19.1 11.0L38.1 22.0" />
      <path d="M38.1 22.0L57.2 11.0" />
      <path d="M38.1 -22.0L38.1 -36.2" />
      <path d="M41.5 -22.0L41.5 -36.2" />
      <path d="M38.1 22.0L38.1 36.2" />
      <path d="M34.7 22.0L34.7 36.2" />
      <text x="38.1" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="38.1" y="44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'flavylium-core': {
    viewBox: '-111.3 -104.0 146.3 142.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -55.0L-38.1 -44.0" />
      <path d="M-38.1 -44.0L-38.1 -32.4" />
      <path d="M-29.1 -16.8L-19.1 -11.0" />
      <path d="M-0.0 -22.0L-0.0 -44.0" />
      <path d="M-0.0 -44.0L-19.1 -55.0" />
      <path d="M-38.1 -44.0L-19.1 -55.0" />
      <path d="M-31.4 -42.9L-21.4 -48.6" />
      <path d="M-38.1 -44.0L-57.2 -55.0" />
      <path d="M-76.2 -88.0L-95.3 -77.0" />
      <path d="M-78.6 -81.6L-88.6 -75.9" />
      <path d="M-95.3 -77.0L-95.3 -55.0" />
      <path d="M-95.3 -55.0L-76.2 -44.0" />
      <path d="M-88.6 -56.1L-78.6 -50.4" />
      <path d="M-76.2 -44.0L-57.2 -55.0" />
      <path d="M-57.2 -55.0L-57.2 -77.0" />
      <path d="M-61.5 -60.2L-61.5 -71.8" />
      <path d="M-57.2 -77.0L-76.2 -88.0" />
      <text x="-38.1" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O+</text>
      </>
    ),
  },
  'silica-tetrahedron': {
    viewBox: '-42.4 -47.2 84.8 79.3',
    art: (
      <>
      <path d="M0.0 -10.4L0.0 -16.4" />
      <path d="M-9.0 5.2L-14.1 8.2" />
      <path d="M9.0 5.2L14.1 8.2" />
      <path d="M5.1 -3.4L4.2 -2.8" />
      <text x="0.0" y="0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">Si</text>
      <text x="0.0" y="-24.2" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-20.9" y="12.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="20.9" y="12.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="9.2" y="-6.2" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'sinigrin': {
    viewBox: '-68.0 -80.2 218.2 138.3',
    art: (
      <>
      <path d="M22.0 0.0L14.9 -12.3" />
      <path d="M3.2 -19.1L-11.0 -19.1" />
      <path d="M-11.0 -19.1L-22.0 -0.0" />
      <path d="M-22.0 -0.0L-11.0 19.1" />
      <path d="M-11.0 19.1L11.0 19.1" />
      <path d="M11.0 19.1L22.0 0.0" />
      <path d="M-11.0 -19.1L-22.0 -38.1" />
      <path d="M-22.0 -38.1L-16.2 -48.2" />
      <path d="M-22.0 -0.0L-33.6 -0.0" />
      <path d="M-11.0 19.1L-16.8 29.1" />
      <path d="M11.0 19.1L16.8 29.1" />
      <path d="M22.0 0.0L44.8 8.3" />
      <path d="M58.9 7.1L71.3 0.0" />
      <path d="M71.3 0.0L82.3 19.1" />
      <path d="M82.3 19.1L101.4 30.1" />
      <path d="M101.4 30.1L120.6 19.1" />
      <path d="M103.1 33.1L122.3 22.1" />
      <path d="M71.3 0.0L71.3 -14.2" />
      <path d="M74.7 0.0L74.7 -14.2" />
      <path d="M78.0 -25.9L83.7 -29.1" />
      <path d="M97.2 -29.1L102.8 -25.9" />
      <path d="M116.3 -25.9L121.9 -29.1" />
      <path d="M118.0 -22.9L123.6 -26.2" />
      <path d="M116.3 -18.1L121.9 -14.9" />
      <path d="M114.6 -15.2L120.2 -11.9" />
      <path d="M109.6 -14.2L109.6 -10.4" />
      <text x="11.0" y="-19.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-11.0" y="-57.2" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-44.0" y="-0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-22.0" y="38.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="22.0" y="38.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="52.1" y="11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">S</text>
      <text x="71.3" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">N</text>
      <text x="90.4" y="-33.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="109.6" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">S</text>
      <text x="128.7" y="-33.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="128.7" y="-11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="109.6" y="0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O-</text>
      </>
    ),
  },
  'lactucin': {
    viewBox: '-73.9 -72.0 144.1 170.7',
    art: (
      <>
      <path d="M0.0 -25.4L-19.8 -15.8" />
      <path d="M-19.8 -15.8L-24.7 5.6" />
      <path d="M-24.7 5.6L-11.0 22.8" />
      <path d="M-11.0 22.8L11.0 22.8" />
      <path d="M11.0 22.8L24.7 5.6" />
      <path d="M24.7 5.6L19.8 -15.8" />
      <path d="M19.8 -15.8L0.0 -25.4" />
      <path d="M-24.7 5.6L-46.6 7.6" />
      <path d="M-46.6 7.6L-55.3 -12.6" />
      <path d="M-55.3 -12.6L-38.7 -27.1" />
      <path d="M-38.7 -27.1L-19.8 -15.8" />
      <path d="M11.0 22.8L17.8 43.8" />
      <path d="M17.8 43.8L-0.0 56.7" />
      <path d="M-0.0 56.7L-11.5 48.3" />
      <path d="M-15.4 36.3L-11.0 22.8" />
      <path d="M0.0 -25.4L-19.8 -15.8" />
      <path d="M-2.5 -19.1L-13.4 -13.9" />
      <path d="M-46.6 7.6L-55.3 -12.6" />
      <path d="M-45.1 0.9L-49.4 -9.1" />
      <path d="M0.0 -25.4L0.0 -47.4" />
      <path d="M-38.7 -27.1L-40.0 -41.2" />
      <path d="M-35.3 -27.4L-36.6 -41.5" />
      <path d="M-0.0 56.7L-0.0 70.9" />
      <path d="M-3.4 56.7L-3.4 70.9" />
      <path d="M17.8 43.8L38.7 50.6" />
      <path d="M16.7 47.0L37.7 53.8" />
      <path d="M-46.6 7.6L-57.9 26.5" />
      <path d="M-57.9 26.5L-52.3 36.6" />
      <path d="M24.7 5.6L36.0 8.2" />
      <text x="-17.8" y="43.8" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-40.7" y="-49.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-0.0" y="78.7" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-47.2" y="45.7" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="46.2" y="10.5" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'lactucopicrin': {
    viewBox: '-73.9 -135.7 178.0 234.4',
    art: (
      <>
      <path d="M0.0 -25.4L-19.8 -15.8" />
      <path d="M-19.8 -15.8L-24.7 5.6" />
      <path d="M-24.7 5.6L-11.0 22.8" />
      <path d="M-11.0 22.8L11.0 22.8" />
      <path d="M11.0 22.8L24.7 5.6" />
      <path d="M24.7 5.6L19.8 -15.8" />
      <path d="M19.8 -15.8L0.0 -25.4" />
      <path d="M-24.7 5.6L-46.6 7.6" />
      <path d="M-46.6 7.6L-55.3 -12.6" />
      <path d="M-55.3 -12.6L-38.7 -27.1" />
      <path d="M-38.7 -27.1L-19.8 -15.8" />
      <path d="M11.0 22.8L17.8 43.8" />
      <path d="M17.8 43.8L-0.0 56.7" />
      <path d="M-0.0 56.7L-11.5 48.3" />
      <path d="M-15.4 36.3L-11.0 22.8" />
      <path d="M0.0 -25.4L-19.8 -15.8" />
      <path d="M-2.5 -19.1L-13.4 -13.9" />
      <path d="M-46.6 7.6L-55.3 -12.6" />
      <path d="M-45.1 0.9L-49.4 -9.1" />
      <path d="M0.0 -25.4L0.0 -47.4" />
      <path d="M-38.7 -27.1L-40.0 -41.2" />
      <path d="M-35.3 -27.4L-36.6 -41.5" />
      <path d="M-0.0 56.7L-0.0 70.9" />
      <path d="M-3.4 56.7L-3.4 70.9" />
      <path d="M17.8 43.8L38.7 50.6" />
      <path d="M16.7 47.0L37.7 53.8" />
      <path d="M-46.6 7.6L-57.9 26.5" />
      <path d="M-57.9 26.5L-52.3 36.6" />
      <path d="M24.7 5.6L38.6 8.8" />
      <path d="M51.5 4.8L61.1 -5.6" />
      <path d="M61.1 -5.6L75.0 -2.4" />
      <path d="M60.4 -2.3L74.2 0.9" />
      <path d="M61.1 -5.6L54.6 -26.6" />
      <path d="M54.6 -26.6L41.7 -46.7" />
      <path d="M41.7 -90.7L22.6 -79.7" />
      <path d="M39.3 -84.3L29.3 -78.5" />
      <path d="M22.6 -79.7L22.6 -57.7" />
      <path d="M22.6 -57.7L41.7 -46.7" />
      <path d="M29.3 -58.8L39.3 -53.0" />
      <path d="M41.7 -46.7L60.7 -57.7" />
      <path d="M60.7 -57.7L60.7 -79.7" />
      <path d="M56.4 -62.9L56.4 -74.4" />
      <path d="M60.7 -79.7L41.7 -90.7" />
      <path d="M41.7 -90.7L41.7 -102.3" />
      <text x="-17.8" y="43.8" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-40.7" y="-49.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-0.0" y="78.7" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-47.2" y="45.7" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="46.2" y="10.5" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="82.6" y="-0.7" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="41.7" y="-112.7" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'betalain-core': {
    viewBox: '-78.7 -67.0 159.8 152.9',
    art: (
      <>
      <path d="M-9.0 -16.8L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M19.1 -11.0L9.0 -16.8" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M-19.1 -11.0L-38.1 -22.0" />
      <path d="M-38.1 -22.0L-50.4 -14.9" />
      <path d="M-39.8 -24.9L-52.1 -17.8" />
      <path d="M-38.1 -22.0L-38.1 -33.6" />
      <path d="M19.1 -11.0L38.1 -22.0" />
      <path d="M38.1 -22.0L38.1 -36.2" />
      <path d="M41.5 -22.0L41.5 -36.2" />
      <path d="M38.1 -22.0L48.2 -16.2" />
      <path d="M-0.0 22.0L-0.0 44.0" />
      <path d="M-3.4 22.0L-3.4 44.0" />
      <path d="M-0.0 44.0L-19.1 55.0" />
      <path d="M-19.1 55.0L-31.4 62.0" />
      <path d="M-20.8 52.0L-33.1 59.1" />
      <text x="0.0" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">NH</text>
      <text x="-57.2" y="-11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-38.1" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="38.1" y="-44.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="57.2" y="-11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-38.1" y="65.9" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      </>
    ),
  },
  'catechin-core': {
    viewBox: '-111.3 -104.0 146.3 142.0',
    art: (
      <>
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-19.1 -11.0L-19.1 11.0" />
      <path d="M-19.1 11.0L-0.0 22.0" />
      <path d="M-12.4 9.9L-2.4 15.6" />
      <path d="M-0.0 22.0L19.1 11.0" />
      <path d="M19.1 11.0L19.1 -11.0" />
      <path d="M14.7 5.8L14.7 -5.8" />
      <path d="M19.1 -11.0L0.0 -22.0" />
      <path d="M0.0 -22.0L-19.1 -11.0" />
      <path d="M-2.4 -15.6L-12.4 -9.9" />
      <path d="M-19.1 -55.0L-38.1 -44.0" />
      <path d="M-38.1 -44.0L-38.1 -29.8" />
      <path d="M-31.4 -18.1L-19.1 -11.0" />
      <path d="M-0.0 -22.0L-0.0 -44.0" />
      <path d="M-0.0 -44.0L-19.1 -55.0" />
      <path d="M-19.1 -55.0L-19.1 -66.6" />
      <path d="M-38.1 -44.0L-57.2 -55.0" />
      <path d="M-76.2 -88.0L-95.3 -77.0" />
      <path d="M-78.6 -81.6L-88.6 -75.9" />
      <path d="M-95.3 -77.0L-95.3 -55.0" />
      <path d="M-95.3 -55.0L-76.2 -44.0" />
      <path d="M-88.6 -56.1L-78.6 -50.4" />
      <path d="M-76.2 -44.0L-57.2 -55.0" />
      <path d="M-57.2 -55.0L-57.2 -77.0" />
      <path d="M-61.5 -60.2L-61.5 -71.8" />
      <path d="M-57.2 -77.0L-76.2 -88.0" />
      <text x="-38.1" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-19.1" y="-77.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      </>
    ),
  },
  'glucosinolate-core': {
    viewBox: '-68.0 -80.2 218.2 138.3',
    art: (
      <>
      <path d="M22.0 0.0L14.9 -12.3" />
      <path d="M3.2 -19.1L-11.0 -19.1" />
      <path d="M-11.0 -19.1L-22.0 -0.0" />
      <path d="M-22.0 -0.0L-11.0 19.1" />
      <path d="M-11.0 19.1L11.0 19.1" />
      <path d="M11.0 19.1L22.0 0.0" />
      <path d="M-11.0 -19.1L-22.0 -38.1" />
      <path d="M-22.0 -38.1L-16.2 -48.2" />
      <path d="M-22.0 -0.0L-33.6 -0.0" />
      <path d="M-11.0 19.1L-16.8 29.1" />
      <path d="M11.0 19.1L16.8 29.1" />
      <path d="M22.0 0.0L44.8 8.3" />
      <path d="M58.9 7.1L71.3 0.0" />
      <path d="M71.3 0.0L78.4 12.4" />
      <path d="M71.3 0.0L71.3 -14.2" />
      <path d="M74.7 0.0L74.7 -14.2" />
      <path d="M78.0 -25.9L83.7 -29.1" />
      <path d="M97.2 -29.1L102.8 -25.9" />
      <path d="M116.3 -25.9L121.9 -29.1" />
      <path d="M118.0 -22.9L123.6 -26.2" />
      <path d="M116.3 -18.1L121.9 -14.9" />
      <path d="M114.6 -15.2L120.2 -11.9" />
      <path d="M109.6 -14.2L109.6 -10.4" />
      <text x="11.0" y="-19.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="-11.0" y="-57.2" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-44.0" y="-0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="-22.0" y="38.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="22.0" y="38.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">OH</text>
      <text x="52.1" y="11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">S</text>
      <text x="82.3" y="19.1" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">R</text>
      <text x="71.3" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">N</text>
      <text x="90.4" y="-33.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="109.6" y="-22.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">S</text>
      <text x="128.7" y="-33.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="128.7" y="-11.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O</text>
      <text x="109.6" y="0.0" fill="currentColor" stroke="none" fontSize="11" fontWeight="600" textAnchor="middle" dominantBaseline="central">O-</text>
      </>
    ),
  },
};
