import { PRINTED_CARDS } from './deck.ts';

/**
 * WHAT EACH PRINTED CARD IS ABOUT, TAXONOMICALLY.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THE BUG THIS EXISTS FOR. A real outdoor goldenrod photograph came back as
 *
 *     Solidago altissima   0.56
 *     Solidago canadensis  0.12
 *     Solidago rugosa      0.10
 *     Solidago juncea      0.07
 *
 * and card #3 prints `Solidago canadensis`, so the 56% answer resolved to `sameGenus` and
 * was refused while the 12% one was offered. Nothing was broken: the matcher did exactly
 * what the card data said. The card data was saying something narrower than the card means.
 *
 * WHY SCOPE IS NOT A GLOBAL "SAME GENUS IS FINE" RULE. Two printed cards share the genus
 * *Rumex* — #2 Broadleaf Dock (*R. obtusifolius*) and #19 Sheep's Sorrel (*R. acetosella*)
 * — so a blanket rule would make every dock claimable as either, which is worse than
 * refusing both. Scope has to be per card, declared, and narrow by default.
 *
 * WHY THIS IS NOT IN `herbs.json`. That file is GENERATED by `scripts/build_deck.py` from
 * the print masters, a full run needs all 45 PDFs, and hand-editing it is forbidden. More
 * importantly it would be the wrong home: coverage is not transcribed from the card, it is
 * a decision about how the MATCHER treats the card. The printed content is untouched.
 * ─────────────────────────────────────────────────────────────────────────────
 */

/**
 * Narrow by default, and that default is the whole safety argument.
 *
 * A card omitted from `CARD_COVERAGE` below is `species`: only its own binomial and the
 * checked synonyms in `plant-match.ts` resolve to it. Broadening is therefore always an
 * explicit, reviewable act, and forgetting to classify a card cannot silently widen it.
 */
export type CardScope =
  /** Only the canonical binomial, plus verified synonyms. */
  | { readonly type: 'species' }
  /**
   * Any species of the genus, except those named in `excluded`.
   *
   * `excluded` exists for a genus where most members belong to the card and a few decidedly
   * do not. Empty today; an entry here is a botanical claim and needs the same standard of
   * evidence as a synonym.
   */
  | { readonly type: 'genus'; readonly excluded?: readonly string[] }
  /**
   * An explicit list of binomials, for a card whose intended grouping does not correspond to
   * one genus. Nothing uses this yet — no printed card has been established to need it —
   * but the matcher handles it, so declaring one is a data change rather than a code change.
   */
  | { readonly type: 'custom'; readonly accepted: readonly string[] };

/**
 * OVERRIDES ONLY. The nine `Genus spp.` cards are not listed: their scope is already stated
 * on the card itself and is derived below, so repeating it here would be two sources of
 * truth for one fact and a chance for them to disagree.
 *
 * EVERY ENTRY IS AN OWNER DECISION ABOUT WHAT A CARD REPRESENTS, not a taxonomic lookup.
 * GBIF can say whether two names denote the same plant — that is what `check_synonyms.py`
 * is for — but no database can say whether the Goldenrod card is meant to cover its genus.
 * So an entry here is added when the owner says so, and never inferred from a common name
 * reading like a genus.
 *
 * The deck already declined that inference once, on the record: a GBIF run for #12 Wild
 * Violet accepted *Viola papilionacea* as a synonym of *V. sororia* and REFUSED
 * *V. riviniana*, *V. odorata*, *V. canina* and *V. septentrionalis* as accepted species in
 * their own right. Wild Violet therefore stays `species` despite a genus-level English name.
 */
export const CARD_COVERAGE: Readonly<Record<string, CardScope>> = {
  /*
   * ─────────────────────────────────────────────────────────────────────────
   * CARDS CONSIDERED FOR GENUS SCOPE AND DELIBERATELY LEFT `species`.
   *
   * Recorded here rather than in a commit message because the next person to read a
   * genus-level English name on a species card will have exactly this idea, and the reasons
   * are not recoverable from the data alone.
   *
   * #1 DANDELION — the closest call, and the evidence is in `ACCEPTED_NAME_SYNONYMS`. The
   * card is ALREADY aggregate-scoped: `taraxacum sect` maps to it, and a section is a
   * supra-specific rank, so the card knowingly covers more than one microspecies. But a
   * SECTION is not the GENUS. *T. erythrospermum* sits in sect. Erythrosperma, a different
   * section, which is precisely why the synonym table's author excluded it by name. Genus
   * scope would overturn a recorded, reasoned decision and would be strictly broader than
   * the aggregate the card actually represents. The identification traits ARE all
   * genus-level (rosette, backward-pointing lobes, single hollow leafless stalk, milky sap,
   * seed clock) and every lookalike is outside Taraxacum — but that is true of most cards
   * and does not by itself establish product intent.
   *
   * #22 BURDOCK — traits are likewise genus-level (woolly pale leaf undersides, purple
   * heads, hooked burs) and the only lookalike is rhubarb, outside Arctium. But there is NO
   * in-repo evidence either way: no Arctium synonyms, no note distinguishing *A. lappa*
   * from *A. minus*, and the card prints a specific binomial. Absent a signal, the narrow
   * reading stands. This one is an owner decision, not a data one.
   *
   * #9 Wood Sorrel, #12 Wild Violet, #23 Wild Mint, #27 Mullein, #29 Field Garlic,
   * #30 Wild Strawberry, #33 Yarrow, #40 Honeysuckle — owner policy, for reasons that are
   * about the plants rather than the deck: Oxalis and Fragaria are too broad to infer
   * equivalence from a common name; Mentha and Lonicera contain species with materially
   * different safety and use profiles and must not be treated as interchangeable; Viola has
   * recorded GBIF evidence against widening; Verbascum, Allium and Achillea each mean the
   * printed species unless a card says otherwise.
   *
   * The through-line: a generic-sounding English name is not evidence of generic intent.
   * ─────────────────────────────────────────────────────────────────────────
   */
  /*
   * #3 GOLDENROD — the card the bug was reported against, and the one scope decision the
   * owner has stated: the card is "Goldenrod" broadly rather than *S. canadensis*
   * specifically. Every North American Solidago the provider returns for a goldenrod
   * photograph — altissima, canadensis, rugosa, juncea — is the plant a player is standing
   * in front of, and the card's own field notes describe the genus-level thing people
   * recognise (a conspicuous golden flower spray, contrasted with ragweed).
   *
   * NO COLLISION: Solidago is represented by exactly one printed card.
   */
  'solidago-canadensis': { type: 'genus' },
};

/**
 * The scope of every printed card, derived once.
 *
 * Two sources, in order: the printed name (`Genus spp.` means the genus — the card says so
 * itself), then `CARD_COVERAGE` as an override. Anything else is `species`.
 */
const SCOPES = new Map<string, CardScope>();
for (const herb of PRINTED_CARDS) {
  const declaredOnCard = /\bspp?\.?$/i.test(herb.scientificName.trim());
  SCOPES.set(
    herb.id,
    CARD_COVERAGE[herb.id] ?? (declaredOnCard ? { type: 'genus' } : { type: 'species' }),
  );
}

/** Every printed card has one; a missing id is a phantom, not a default. */
export function scopeFor(herbId: string): CardScope | undefined {
  return SCOPES.get(herbId);
}

/** For tests and reporting: the full classification, in card order. */
export function allScopes(): { herbId: string; scope: CardScope }[] {
  return PRINTED_CARDS.map((herb) => ({ herbId: herb.id, scope: SCOPES.get(herb.id)! }));
}

/**
 * The printed cards whose scope is broader than their own binomial, with that scope.
 *
 * The name-matching itself lives in `plant-match.ts`, which owns `normalizeName` and
 * `genusOf`. Keeping it there rather than importing those here is what makes the dependency
 * one-way: this module is data plus a regex on the printed name, and the matcher reads it.
 * The other direction would be a cycle, and under Deno — where this module travels with the
 * matcher into `_shared/herbdex/` — a cycle is a deploy failure rather than a warning.
 */
export function broadenedCards(): { herbId: string; scientificName: string; scope: CardScope }[] {
  return PRINTED_CARDS.filter((herb) => SCOPES.get(herb.id)?.type !== 'species').map((herb) => ({
    herbId: herb.id,
    scientificName: herb.scientificName,
    scope: SCOPES.get(herb.id)!,
  }));
}
